apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terricom
resources:
  - ../../base
  - externalsecret.yaml
images:
  - name: terricom-web
    newName: ghcr.io/terricom/terricom-web
    newTag: '1.0.0'
  - name: terricom-tools
    newName: ghcr.io/terricom/terricom-tools
    newTag: '1.0.0'
patches:
  - target: { kind: ConfigMap, name: terricom-config }
    patch: |-
      - op: replace
        path: /data/APP_URL
        value: https://terricom.fr
