<?php
declare(strict_types=1);

namespace App\Admin;

/**
 * Bulles d'aide « ? » du back-office : un texte court par écran, par bloc et par champ.
 * Le script du back-office les place à côté du titre de l'écran (.top__h), des titres de
 * blocs (.card__t) et des libellés de champs (.f__k) dont le texte correspond à une clé
 * (en minuscules). Les textes sont rédigés ici, en un seul endroit.
 */
final class Tips
{
    /** Blocs et champs présents sur plusieurs écrans. */
    private const COMMON = [
        // Panneaux de l'éditeur de fiche
        'publication' => 'Choisissez le statut : <b>Brouillon</b> (invisible), <b>À relire</b>, <b>Planifié</b> (publication automatique à la date choisie) ou <b>Publié</b>. Enregistrez avec le bouton ou <b>Ctrl + S</b> ; une note de version aide à retrouver une modification.',
        'orthographe' => 'Le correcteur relit tous les textes de l’écran : orthographe, accords, conjugaison et syntaxe (avec Gemini), plus les règles du musée (« 1re », « 2e », « À »…). Il propose, vous décidez : « Corriger », « Ignorer », ou « + Dictionnaire » pour un nom propre. Rien n’est enregistré avant « Enregistrer ».',
        'recherche sur le web' => 'L’IA cherche avec Google ce qui pourrait corriger ou compléter cette fiche (score, buteurs, affluence, arbitre, naissance, parcours…) et propose, avec ses sources : divergences avec la fiche, compléments, pistes à consulter. Rien n’est modifié : ouvrez la source, vérifiez, puis reportez vous-même (« Copier » aide). Seulement quand vous cliquez ; le dernier résultat reste consultable 30 jours (environ 1 centime la recherche).',
        'écouter la fiche' => 'L’explication audio que les visiteurs écoutent sur cette fiche (3 minutes au plus par défaut, Réglages › Fiches audio). Modifiez le texte puis « Garder ce texte », ou « Rédiger avec l’IA ». « Voix IA » enregistre une voix naturelle (environ 3 centimes pour 3 minutes) ; sinon, c’est la voix du navigateur du visiteur, gratuite.',
        'mis à jour automatiquement' => 'Ce que le site recalcule seul quand vous enregistrez cette fiche : saison, fiches des joueurs, carte, records, image de partage… Rien à faire de votre côté.',
        'contrôle qualité' => 'Les vérifications propres à cette fiche : score cohérent, photos sans crédit, image à la une manquante… Une alerte disparaît dès que la fiche est corrigée.',
        'version en' => 'État de la traduction anglaise de cette fiche. « À revoir » : le français a changé depuis la traduction.',
        'version anglaise' => 'Texte anglais de la fiche. Laissez vide pour afficher le français ; le bouton « Traduire » propose une traduction par l’IA, à relire.',
        'tableaux' => 'Tableaux de la fiche (statistiques, compositions d’autres équipes…). Cliquez dans une case pour la modifier ; « Coller un tableau » importe un tableau copié depuis Excel, Word ou une page web.',
        'rubriques' => 'Les rubriques où la fiche apparaît (mosaïques et menus). Une fiche peut être dans plusieurs rubriques ; la saison d’un match est ajoutée automatiquement.',
        'référencement' => 'Ce que Google et les réseaux sociaux affichent : titre, description et adresse de la page. Laissés vides, ils sont remplis automatiquement.',
        'galerie' => 'Les photos affichées en galerie sur la fiche. Ajoutez-les depuis la médiathèque, glissez pour changer l’ordre ; le crédit de la médiathèque s’applique si celui de la galerie est vide.',
        'vidéos' => 'Collez le lien d’une vidéo YouTube, Dailymotion, Vimeo ou Rutube. Elle ne se charge qu’après l’accord du visiteur (cookies), avec son image en attendant.',
        'publications intégrées' => 'Messages de réseaux sociaux (X, Facebook…) cités dans la fiche : le lien et le texte, affichés sans charger le réseau social.',
        'images dans le texte' => 'Images insérées au fil du texte (reprises de l’ancien site). Pour les nouvelles fiches, préférez la galerie.',
        'encart « chiffre clé »' => 'Le grand chiffre mis en avant sur la fiche (ex. « 16 063 spectateurs »), avec sa légende.',
        // Champs
        'titre de la fiche' => 'Le titre affiché en haut de la fiche et dans les mosaïques. Pour un match, il est proposé automatiquement à partir des équipes et de la date.',
        'titre (google & partage)' => 'Titre montré par Google et les réseaux sociaux. Vide : le titre de la fiche est utilisé.',
        'description' => 'Une ou deux phrases qui donnent envie de cliquer dans les résultats de Google (160 caractères environ). Vide : le début du texte est utilisé.',
        'adresse de la page' => 'L’adresse (URL) de la fiche, créée automatiquement avec des mots-clés. Si vous la changez après publication, l’ancienne adresse est redirigée vers la nouvelle.',
        'date de publication' => 'Date de mise en ligne de la fiche (ordre « plus récentes » des mosaïques). Pour publier plus tard, utilisez le statut « Planifié ».',
        'à la une (slider de l’accueil, tirage aléatoire)' => 'Cochée, la fiche peut apparaître dans le grand slider de l’accueil (tirage au hasard parmi les fiches « À la une » qui ont une image).',
        'image à la une (mosaïques, partage, en-tête)' => 'La photo principale : vignette dans les mosaïques, image de partage sur les réseaux sociaux et en-tête de la fiche. Choisissez une photo de bonne taille, créditée.',
        'intertitre' => 'Titre d’une partie du texte (ex. « Avant-match », « Résumé »). Il structure la page et aide Google.',
        'lien de la vidéo' => 'Adresse de la vidéo copiée depuis YouTube, Dailymotion, Vimeo ou Rutube (barre d’adresse ou bouton « Partager »).',
        'crédit' => 'Auteur ou source de la photo (photographe, journal, collection). Obligatoire pour toute photo publiée.',
        'légende' => 'Le texte d’accompagnement : pour une photo, ce qu’elle montre (qui, où, quand), affiché dessous et lu aux personnes malvoyantes ; pour un chiffre clé, ce qu’il représente.',
        'fiches liées' => 'Fiches en rapport (match, joueur…) : tapez quelques lettres du titre et choisissez dans la liste.',
        'introduction' => 'Quelques lignes d’ouverture affichées avant les blocs de texte (facultatif).',
        'chiffre' => 'Le grand nombre de l’encart (ex. « 147 ») ; la légende dit ce qu’il représente.',
        'aperçu google' => 'Comment la fiche apparaît dans les résultats de Google, d’après le titre et la description enregistrés.',
        'image de partage générée' => 'L’image créée automatiquement pour les partages sur les réseaux sociaux (photo, titre, score…). Elle se met à jour à chaque enregistrement.',
        'publication programmée le' => 'Date et heure de mise en ligne automatique pour le statut « Planifié » (la tâche planifiée publie la fiche à quelques minutes près).',
        'note de version' => 'Facultatif : un mot sur ce que vous avez changé (« score corrigé d’après L’Est républicain »). Il apparaît dans l’onglet Historique.',
    ];

    /** Par écran (clé du menu) : 'screen' pour le titre de l'écran, puis blocs et champs. */
    private const SCREENS = [
        'dash' => [
            'screen' => 'Votre point de départ : chiffres du musée, travail récent de l’équipe, publications programmées et liste « À faire » des points à reprendre.',
            'à faire' => 'Les tâches qui attendent quelqu’un : contributions à traiter, photos à créditer, joueurs sans fiche… Cliquez pour ouvrir l’écran concerné.',
            'activité récente' => 'Les dernières modifications de toute l’équipe (le détail complet est dans Pilotage › Journal).',
            'audience · 30 jours' => 'Pages vues sur le site public, mesurées sans cookie ni adresse IP.',
            'publications programmées' => 'Les fiches au statut « Planifié » et leur date de mise en ligne automatique.',
        ],
        'qualite' => ['screen' => 'Tout ce qui mérite une vérification, classé par onglet : statistiques incohérentes, liens joueurs, orthographe et syntaxe, photos sans crédit, lieux de naissance inconnus, traductions. Corrigez la fiche : l’alerte disparaît d’elle-même.'],
        'dictionnaire' => [
            'screen' => 'Les mots que le correcteur d’orthographe ne doit jamais corriger : noms propres, surnoms, mots du club ou du patois. Les noms des joueurs, des clubs et des stades du musée sont déjà reconnus. Un mot s’ajoute aussi depuis le correcteur, bouton « + Dictionnaire ».',
            'mot ou expression' => 'Écrit exactement comme il doit l’être (majuscules et accents compris). Il ne sera plus jamais signalé, sur aucune fiche.',
            'remarque' => 'Facultatif : pourquoi ce mot est juste (surnom, ancien nom, mot local…), pour les autres historiens.',
        ],
        'journal' => ['screen' => 'Qui a fait quoi et quand dans le back-office. Filtrez par personne ; utile pour retrouver une modification récente.'],
        'matchs' => [
            'screen' => 'Les fiches match. La liste se filtre par saison, compétition et statut ; dans une fiche, les onglets Infos, Compo & événements, Récit, Médias… se remplissent dans l’ordre que vous voulez.',
            'score' => 'Buts de chaque équipe (domicile puis extérieur). Prolongation et tirs au but sont facultatifs. Le résultat (victoire, nul, défaite) est déduit automatiquement.',
            'composition sochaux' => 'Une ligne par joueur : poste (G, D, M, A, R remplaçant, E entraîneur), numéro, nom, buts, remplacement, cartons. Choisissez le joueur dans la liste proposée pour relier sa fiche (✓) ; « Importer depuis un tableau » colle une composition copiée.',
            'temps forts (minute par minute)' => 'Les actions marquantes avec leur minute ; cochez « But » et indiquez le score pour les buts. Ils forment la frise du résumé sur la fiche.',
            'réactions' => 'Citations d’après-match : qui parle et ce qu’il a dit.',
            'brèves' => 'Petites informations autour du match (anecdotes, transferts, blessures).',
            'date' => 'Date du match (jj/mm/aaaa). Elle place le match dans sa saison et dans « Ce jour-là ».',
            'compétition' => 'Famille de compétition (championnat, Coupe de France…) : elle sert aux filtres, bilans et records.',
            'libellé' => 'Nom exact de la compétition affiché sur la fiche (ex. « Ligue 2 », « Coupe de la Ligue »).',
            'journée / tour' => 'Ex. « J12 » ou « 32e de finale ».',
            'adversaire' => 'Le club rencontré : choisissez-le dans la liste pour que le face-à-face et le logo suivent.',
            'stade' => 'Nom du stade (et ville entre parenthèses si besoin). Il alimente la carte des stades et les bilans par stade.',
            'spectateurs' => 'Nombre de spectateurs, en chiffres. Il sert aux records d’affluence.',
            'buteurs (texte de l’en-tête)' => 'La ligne des buteurs telle qu’affichée en tête de fiche, si elle diffère des buteurs par équipe.',
            'buts par équipe' => 'Pour chaque équipe, la liste des buteurs avec les minutes (ex. « Prat 33’, Thomas 78’ »).',
            'événement (match particulier)' => 'Pour un match à part (jubilé, finale, inauguration) : un mot qui le met en valeur.',
            'prolongation' => 'Non, après prolongation (a.p.) ou tirs au but : avec « Tirs au but », deux champs apparaissent pour le score de la séance.',
            'domicile / extérieur' => 'Sochaux reçoit (domicile) ou se déplace (extérieur) : cela fixe l’ordre des équipes dans le titre et le score.',
            'niveau adversaire' => 'La division de l’adversaire à l’époque (ex. « D2 », « N1 », « L1 Sui ») : affichée sous son nom.',
            'niveau sochaux' => 'La division de Sochaux à l’époque (ex. « D1 », « L2 »).',
            'arbitre' => 'Nom de l’arbitre, tel qu’on le trouve dans la presse (ex. « M. Wurtz »).',
            'lignes complémentaires de l’en-tête' => 'Informations affichées sous le score, une par ligne (ex. buteurs de l’adversaire, expulsion, mention particulière).',
            'match.highlights:min.' => 'Minute de l’action (ex. « 33 » ou « 90+2 »).',
            'match.highlights:action' => 'Ce qui se passe, en une phrase : la ligne s’affiche dans la frise « Résumé » de la fiche.',
            'match.highlights:but' => 'À cocher pour un but : la ligne est mise en valeur avec la mention « But ! » et le score.',
            'match.highlights:score' => 'Score juste après le but (ex. « 1-0 ») ; affiché seulement pour les actions cochées « But ».',
        ],
        'personnes' => [
            'screen' => 'Les fiches des joueurs, entraîneurs, dirigeants et personnages. Leurs matchs, buts et cartons sont reliés automatiquement depuis les compositions.',
            'identité' => 'Nom, prénom, rubriques et poste. La première rubrique cochée donne l’adresse de la fiche (/joueurs/…, /entraineurs/…).',
            'naissance' => 'Date et lieu de naissance : la ville place la personne sur la carte des origines (position trouvée automatiquement, modifiable).',
            'décès' => 'Date et lieu de décès, si connus.',
            'statuts & carto' => 'Formé au club, international, à l’essai, légende (mise en avant) et présence sur la carte.',
            'carte de l’album du centenaire' => 'La carte à collectionner du joueur : présence dans l’album, numéro et rareté.',
            'au club' => 'Arrivée, départ, premiers et derniers matchs. Les dates d’arrivée et de départ aident aussi à relier les compositions au bon joueur.',
            'palmarès' => 'Titres et distinctions, une ligne par titre.',
            'après sochaux' => 'La suite du parcours, une ligne par étape.',
            'fiche d’identité (tableau d’origine)' => 'Le tableau d’identité de l’ancien site, conservé tel quel (libellé et valeur).',
            'matchs marquants' => 'Quelques matchs à mettre en avant sur la fiche : tapez une équipe ou une date et choisissez.',
            'matchs reliés automatiquement' => 'Tous les matchs où la personne figure dans une composition, avec ses buts et son temps de jeu. Rien à saisir : ajoutez un nom mal écrit dans « Autres graphies ».',
            'statistiques (tableau saison par saison)' => 'Le tableau de statistiques saison par saison, modifiable comme une feuille de calcul.',
            'nom affiché' => 'Le nom tel qu’il apparaît sur le site. Vide : « Prénom Nom ».',
            'autres graphies dans les compositions' => 'Les autres façons dont le nom est écrit dans les compositions (« CAMARA Razza »…) : ces matchs seront reliés à cette fiche.',
            'ligne (filtres, terrain)' => 'Gardien, défenseur, milieu ou attaquant : sert aux filtres de la rubrique Nos Lions et au placement sur le terrain.',
            'latitude' => 'Calculée automatiquement à partir de la ville ; à corriger seulement si le point est mal placé sur la carte.',
            'longitude' => 'Calculée automatiquement à partir de la ville ; à corriger seulement si le point est mal placé sur la carte.',
            'légende (mise en avant)' => 'Met la personne en valeur (cartes, sélections, page d’accueil).',
            'visible sur la carto' => 'Décochez pour ne pas afficher la personne sur la carte des origines.',
            'à l’essai' => 'Joueur venu à l’essai sans signer : la fiche le précise.',
            'surnom' => 'Affiché sous le nom, entre guillemets, en tête de fiche.',
            'poste (texte)' => 'Le poste en toutes lettres (ex. « défenseur latéral droit »), affiché sur la fiche et sur la carte du joueur.',
            'numéros portés' => 'Les numéros de maillot portés au club (ex. « 9, 14 »).',
            'sous-titre (accroche sous le nom)' => 'Une phrase d’accroche affichée sous le nom, en tête de fiche.',
            'sélections internationales' => 'Une ligne par sélection (ex. « France A : 3 sélections ») : le total est calculé pour la carte du joueur.',
            'rareté' => 'Légende, Classique ou Actuel : l’apparence de la carte dans l’album (une carte « Légende » se débloque aussi en réussissant le quiz).',
            'numéro de la carte' => 'Le numéro de la carte dans l’album (1 à 120).',
            'arrivée (joueur)' => 'Mois et année d’arrivée (ex. « juillet 1980 ») : ils datent la période au club et aident à relier les compositions.',
            'départ (joueur)' => 'Mois et année de départ (ex. « juin 1987 »).',
            'période d’essai' => 'Pour un joueur venu à l’essai : quand (ex. « été 1985 »).',
            'premier match' => 'Ex. « 12/08/1978 contre Nancy ». Avec une date jj/mm/aaaa, le match est relié ; ces repères alimentent « Ses matchs marquants » si aucun match marquant n’est choisi.',
            'premier but' => 'Même principe que « Premier match » : une date jj/mm/aaaa relie le match.',
            'dernier match' => 'Même principe que « Premier match » : une date jj/mm/aaaa relie le match.',
            'premier match comme entraîneur' => 'Même principe que « Premier match » : une date jj/mm/aaaa relie le match.',
            'dernier match comme entraîneur' => 'Même principe que « Premier match » : une date jj/mm/aaaa relie le match.',
        ],
        'articles' => [
            'screen' => 'Articles thématiques (infrastructures, symboles, supporters, bilans de saison…) et pages du site (dont les pages légales).',
            'type d’article' => 'Article, bilan de saison, portrait ou dossier : change la présentation et les liens automatiques (un bilan est relié à sa saison).',
            'saison (bilan)' => 'Pour un bilan de saison : la saison concernée (ex. 1987-1988).',
            'chapeau / surtitre' => 'La courte phrase au-dessus ou sous le titre qui résume l’article.',
        ],
        'objets' => [
            'screen' => 'Les objets des réserves du musée (maillots, affiches, programmes, coupures de presse…), présentés dans la rubrique « Réserves ».',
            'collection' => 'La collection des réserves où l’objet est rangé (maillots, affiches…).',
            'provenance' => 'D’où vient l’objet (don, prêt, collection privée).',
            'crédit / propriétaire' => 'À qui appartient l’objet ou qui l’a photographié.',
        ],
        'moments' => [
            'screen' => '« 100 ans, 100 moments » : un moment de l’histoire du club par semaine jusqu’au centenaire (20 mai 2028). Les moments pas encore révélés changent de semaine avec ↑ / ↓ ou l’icône quatre flèches, puis « Enregistrer le calendrier ».',
            'numéro (1 à 100)' => 'Le rang du moment dans la série ; il fixe sa semaine de publication.',
        ],
        'referentiels' => ['screen' => 'Les listes communes : adversaires (regroupement des variantes de noms, ville, logo), stades et lieux (position sur la carte). Une correction ici s’applique à toutes les fiches.'],
        'medias' => ['screen' => 'Toutes les photos et PDF du musée. Envoyez par glisser-déposer (crédit demandé), cliquez une photo pour la légende, les droits, la retouche ou le remplacement ; les filtres montrent ce qu’il reste à compléter.'],
        'accueil' => [
            'screen' => 'La page d’accueil du site : slider, bandeau défilant, chiffres, grandes époques, réserves, encarts. Chaque bloc s’enregistre avec le bouton en bas de page.',
            'grand slider de l’accueil' => 'Tirage au hasard parmi les fiches cochées « À la une » (avec image), comme sur l’ancien site, ou liste choisie à la main dans l’ordre voulu.',
            'bandeau « en direct du musée »' => 'Le bandeau défilant en haut du site : messages automatiques (Ce jour-là, centenaire, dernier match fiché) et messages de l’équipe, avec lien facultatif.',
            'compteurs et centenaire' => 'Les chiffres de l’accueil (membres, vidéos…) et la date du centenaire pour le compte à rebours.',
            'les grandes époques' => 'Les périodes de l’histoire du club présentées sur l’accueil : nom, dates, texte, image et dates clés.',
            'les réserves du musée' => 'Les collections d’objets mises en avant sur l’accueil.',
            'palmarès (bandeau jaune)' => 'Le bandeau des titres du club : chiffre (années) et titre.',
            '« ils ont porté le lion »' => 'Les joueurs cochés « Légende » dans leur fiche : quatre sont tirés au hasard à chaque visite (à défaut, les plus capés).',
            'images des encarts' => 'Les images des encarts Quiz, Maillots, Frise et Contribuer.',
            'référencement de l’accueil' => 'Titre et description de l’accueil pour Google et les réseaux sociaux.',
            'contenu du slider' => '« Tirage au hasard » parmi les fiches « À la une » (comme sur l’ancien site) ou « Sélection manuelle » : vous choisissez les fiches et leur ordre.',
            'fiches du slider, dans l’ordre' => 'Tapez le titre d’une fiche et choisissez-la ; glissez pour changer l’ordre. Les fiches sans image à la une ou non publiées sont ignorées.',
            'messages de l’équipe' => 'Vos messages dans le bandeau : étiquette (ex. « Nouveau »), texte, lien facultatif et version anglaise. Décochez « Affiché » pour masquer un message sans le supprimer.',
            'titre de la page d’accueil (onglet du navigateur, google)' => 'Le titre de l’accueil dans l’onglet du navigateur et dans les résultats de Google.',
            'présentation du musée (description pour google et le partage)' => 'La présentation du musée reprise par Google et lors des partages de l’accueil.',
            'nombre de slides tirées au hasard dans « à la une »' => 'Combien de fiches le slider tire au hasard à chaque visite (1 à 12).',
            'compteur : membres de la communauté' => 'Chiffre affiché tel quel sur l’accueil (ex. « 11000+ ») : à mettre à jour à la main. Les nombres de matchs et de joueurs, eux, sont calculés.',
            'compteur : vidéos youtube' => 'Chiffre affiché tel quel sur l’accueil (ex. « 1400+ ») : à mettre à jour à la main.',
            'date du centenaire (compte à rebours)' => 'La date visée par le compte à rebours du site (20 mai 2028).',
            'dates clés' => 'Quelques repères de l’époque (année et fait), affichés avec son texte.',
            'lien « visiter cette époque »' => 'L’adresse ouverte par le bouton de l’époque (ex. « /interactif/frise/#1928 »).',
            'identifiant (adresse)' => 'Le mot de l’adresse de la collection : /reserves/identifiant/ (minuscules, sans espace ni accent).',
        ],
        'rubriques' => [
            'screen' => 'Les rubriques du site (catégories de l’ancien WordPress) : libellés, menus et ordre des fiches dans les mosaïques.',
            'libellés' => 'Nom de la rubrique en français et en anglais, tel qu’affiché dans les menus et les mosaïques.',
            'menu' => 'Place de la rubrique dans les méga-menus.',
            'ordre des fiches' => 'L’ordre manuel des fiches de la rubrique (sous-rubriques comprises) : ↑ / ↓ pour un cran, icône quatre flèches pour glisser plus loin (le trait jaune montre la position), clic sur un numéro pour taper la position. Puis Enregistrer.',
            'ordre d’affichage sur le site' => 'Ordre que les visiteurs voient d’abord dans la mosaïque : manuel (liste ci-dessous), chronologique ou alphabétique. Ils peuvent toujours changer de tri.',
            'ordre des sous-rubriques' => 'Ordre des saisons, compétitions… dans les menus, onglets et filtres : ↑ / ↓ ou icône quatre flèches, puis Enregistrer.',
            'sous-rubriques' => 'Les rubriques contenues dans celle-ci (onglets de la mosaïque).',
            'texte d’introduction de la mosaïque' => 'Le court texte affiché en tête de la mosaïque.',
            'adresse' => 'L’adresse de la rubrique. Les anciennes adresses WordPress y sont redirigées.',
        ],
        'redirections' => [
            'screen' => 'Les anciennes adresses redirigées vers les nouvelles (301), et l’onglet « Adresses introuvables » : les adresses demandées par des visiteurs qui n’existent pas, à rediriger en un clic.',
            'nouvelle redirection' => 'Ancienne adresse (commençant par /) et nouvelle adresse : les visiteurs et Google sont envoyés vers la nouvelle.',
        ],
        'attente' => [
            'screen' => 'Une page d’attente remplace le site pendant une opération (logo, texte, compte à rebours facultatif). Les membres connectés du back-office voient toujours le site ; « Aperçu » montre la page d’attente.',
            'logo' => 'Le logo de la page d’attente. Vide : logo Sochaux Rétro.',
            'titre' => 'Le grand titre de la page d’attente (ex. « Le musée ouvre bientôt ses portes »).',
            'date et heure cibles du compte à rebours' => 'Le moment visé par le compte à rebours (ex. la réouverture du site).',
            'intitulé du compte à rebours' => 'Le texte au-dessus du compte à rebours (ex. « Ouverture dans »).',
        ],
        'interactif' => [
            'screen' => 'Les outils interactifs du site : quiz, frise, maillots, carte (épopées, lieux), partenaires, page « Faire un don ». Chaque outil est une liste d’éléments à compléter, réordonner ou traduire.',
            'textes' => 'Les textes d’introduction de l’outil, en français et en anglais.',
            'dernières modifications' => 'L’historique des modifications de cet outil (qui, quand).',
            'onze de légende' => 'Le vote du public pour le Onze du centenaire : candidats et date de révélation du résultat.',
            'album du centenaire' => 'Les cartes à collectionner : choisissez les joueurs dans leur fiche (onglet Identité).',
            'carte des stades' => 'Les stades viennent des fiches match ; leur position se corrige dans Saisons, adversaires, lieux.',
            '100 moments' => 'La série hebdomadaire du centenaire (menu Éditorial › 100 moments).',
            'quiz supporters' => 'Les questions du quiz : six sont tirées au hasard à chaque partie parmi les questions affichées. Celles préparées au lancement sont à valider par un historien.',
            'frise chronologique' => 'Les dates de la frise (triées automatiquement par année), avec texte, image, lien et mise en valeur.',
            'comparateur de maillots' => 'Une photo de maillot par époque, de préférence cadrée de la même façon (de face, fond neutre).',
            'carte : grandes épopées' => 'Finales et grands matchs européens placés sur la carte. Sans coordonnées, l’étape n’apparaît pas.',
            'carte : lieux du club' => 'Stades d’entraînement, sièges, lieux de mémoire… affichés sur la carte.',
            'partenaires' => 'Les logos des partenaires, affichés dans cet ordre sur la page Contact & partenaires.',
            'réponses (4)' => 'Les quatre réponses proposées ; indiquez la bonne dans « Bonne réponse ».',
            'le saviez-vous ? (après la réponse)' => 'L’anecdote affichée après la réponse, qu’elle soit juste ou fausse.',
            'mise en valeur' => 'Couleur de la date sur la frise : jaune pour un titre ou un trophée, marine pour une date clé.',
            'coordonnées' => 'Latitude et longitude du lieu (ex. 47.5122 et 6.8111). Dans OpenStreetMap ou Google Maps, un clic droit sur le lieu donne ces deux nombres ; le lien « Vérifier sur OpenStreetMap » contrôle le point.',
        ],
        'onze' => [
            'screen' => 'Le vote « Onze de légende du centenaire » et la sélection des cartes de l’album.',
            'le onze du public' => 'Le résultat des votes à ce jour, poste par poste.',
            'date de dévoilement' => 'Date à laquelle le Onze du public est révélé sur le site.',
        ],
        'retro' => [
            'screen' => 'Le Rétro-Direct rejoue un grand match en direct sur le site, minute par minute, le jour de son anniversaire et à l’heure du coup d’envoi : score, buts, remplacements, mi-temps. Aucune IA, aucun coût.',
            'au programme' => 'Les directs à venir et passés : « Voir » ouvre la page publique, « Modifier » change la date, l’heure ou la présentation, « Retirer » l’enlève du programme (le match reste à revivre en accéléré). Pour un direct passé : le pic de spectateurs connectés et les réactions.',
            'programmer un match' => 'Choisissez un match (au moins ' . \App\Services\RetroDirect::MIN_EVENTS . ' temps forts avec leur minute), la date et l’heure du coup d’envoi. La date de son prochain anniversaire est proposée.',
            'modifier le direct' => 'Changez la date, l’heure du coup d’envoi ou la présentation de ce direct.',
            'présentation' => 'Quelques lignes affichées avant le coup d’envoi et dans l’agenda : le contexte du match, l’enjeu, une anecdote. Sans spoiler du score !',
            'anniversaires à venir' => 'Les matchs dont c’est l’anniversaire rond (10, 20, 25, 30, 40, 50 ans…) dans la période choisie, avec assez de temps forts. « Intérêt » additionne temps forts, coupe, finale, victoire, gros score, affluence et fiche à la une. « Programmer à 20 h » l’ajoute en un clic (heure modifiable ensuite).',
        ],
        'souvenirs' => [
            'screen' => 'Les Après-midi Bonal : chaque mois, un kit de 4 pages en gros caractères à imprimer pour les anciens supporters (le grand match d’il y a N ans, des visages à reconnaître, un quiz, « Racontez-nous »). Tout est fabriqué automatiquement ; ici, vous pouvez choisir le match et ajouter un mot d’introduction.',
            'match du mois' => '« Automatique » retient le match le plus marquant joué ce mois-là (temps forts, coupe, anniversaire rond, 30 à 60 ans d’âge, belle photo). Les autres propositions sont classées par intérêt ; « Ou un autre match » permet de choisir n’importe quelle fiche.',
            'mot d’introduction' => 'Quelques lignes affichées en tête du récit du match dans le PDF : le contexte, l’enjeu, une anecdote.',
            'ils y étaient' => 'Les témoignages publiés sur les fiches de match. Un témoignage reçu par « Contribuer » se publie à la validation (Communauté › Contributions), avec un texte et une signature que vous pouvez relire.',
        ],
        'contributions' => [
            'screen' => 'Les propositions des visiteurs (corrections, photos, documents). Traitez-les : demander une précision, publier (les fichiers vont dans la médiathèque ou une fiche) ou refuser.',
            'décision' => 'Publier la contribution, demander une information à son auteur ou la refuser (il est prévenu par e-mail).',
            'fichiers' => 'Les fichiers envoyés : cliquez pour les voir avant de les publier.',
            'publier les fichiers' => 'Verse les fichiers dans la médiathèque, avec le crédit et la cession de droits indiqués par l’auteur, et peut les rattacher à une fiche.',
            'échanges' => 'Les messages échangés avec l’auteur de la contribution.',
        ],
        'messages' => [
            'screen' => 'Les messages du formulaire de contact. Répondez par e-mail, attribuez à un membre de l’équipe, marquez comme traité.',
            'répondre par e-mail' => 'Votre réponse part par e-mail à l’expéditeur et reste dans l’historique du message.',
            'suivi' => 'Statut du message (nouveau, lu, traité) et personne chargée de la réponse.',
        ],
        'newsletter' => [
            'screen' => 'La lettre hebdomadaire « Ce jour-là » : les matchs joués cette semaine-là dans l’histoire, envoyée automatiquement aux abonnés.',
            'abonnés' => 'Les inscrits (confirmés par e-mail). Chacun peut se désinscrire d’un clic.',
            'prochaine lettre' => 'L’aperçu de la prochaine lettre ; « Envoi de test » l’envoie à votre adresse.',
            'dernier envoi' => 'Date et nombre de destinataires du dernier envoi.',
        ],
        'dons' => [
            'screen' => 'Le suivi de la collecte : jauge, dons reçus (carte, PayPal, hors ligne), dons mensuels, export.',
            'enregistrer un don hors ligne' => 'Pour un chèque, un virement ou des espèces (administrateurs) : il compte dans la jauge et peut figurer sur le mur des donateurs.',
            'dons reçus hors ligne' => 'Les dons par chèque, virement ou espèces sont enregistrés par un administrateur.',
            'mur des donateurs' => 'Les donateurs qui ont accepté d’afficher leur nom sur le site.',
            'paiements' => 'Les paiements reçus pour ce don (un par mois pour un don mensuel).',
            'reçus fiscaux' => 'Fonction prête mais désactivée : à activer dans les réglages seulement si l’association y a droit. Les reçus sont émis et consultés par les administrateurs.',
            'note interne' => 'Une note visible seulement dans le back-office.',
            'don mensuel' => 'État de l’abonnement (actif, arrêté) chez le prestataire de paiement.',
            'moyen' => 'Chèque, virement, espèces ou autre : comment le don a été reçu.',
            'nom sur le mur' => 'Le nom à afficher sur le mur des donateurs. Vide : le don reste discret.',
            'maintenance' => 'Synchroniser va chercher chez Stripe et PayPal les paiements éventuellement manqués (c’est aussi fait toutes les heures) ; Recalculer remet la jauge à jour.',
        ],
        'traductions' => ['screen' => 'La version anglaise : libellés de l’interface (boutons, menus) et traduction des fiches par l’IA, à relire. Le français fait toujours foi.'],
        'assistant' => ['screen' => 'L’assistant IA du site (bulle en bas à droite) : questions posées par les visiteurs, avis, export et réindexation après de grosses modifications.'],
        'audio' => [
            'screen' => 'Chaque fiche est expliquée à voix haute (bouton « Écouter » sur le site), en entier, dans la durée maximale réglée. Gratuit avec la voix du navigateur ; voix naturelle de Gemini fiche par fiche (éditeur) ou pour tout le musée en traitement groupé, à moitié prix.',
            'tout le musée en voix ia' => 'Estime le coût puis confie toutes les fiches sans voix IA à jour au traitement groupé de Google (résultats en quelques heures). Le coût réel s’affiche dans Coûts IA.',
            'traitements groupés' => 'Chaque envoi à Google et son état : en attente, chez Google, rangement des voix, terminé. La tâche planifiée s’en occupe seule ; « Annuler » arrête un envoi en cours.',
            'dernières voix ia' => 'Les dernières voix enregistrées : ▶ pour les écouter, le titre pour ouvrir la fiche.',
            'pages de synthèse racontées par l’ia' => 'Face-à-face, saisons, bilans, records et chiffres racontés par l’IA, en français et en anglais, puis lus par la voix IA enregistrée. Essayez d’abord sur une page (son adresse, par exemple /face-a-face/nancy/), puis « Lancer pour tout le musée » : rien n’est dépensé avant. Ensuite, chaque nuit, les récits manquants ou dont les chiffres ont changé sont rédigés et enregistrés. En attendant, le récit automatique est lu par la voix du navigateur.',
        ],
        'couts' => [
            'screen' => 'Ce que coûte l’IA (Gemini), calculé à chaque appel : aujourd’hui, ce mois-ci et ce que l’association doit rembourser. Les chiffres se mettent à jour seuls toutes les 10 secondes.',
            'derniers appels' => 'Les 30 derniers appels du mois : qui les a demandés (membre, visiteur via l’assistant, tâche automatique), la fiche concernée, les jetons envoyés → produits et le coût. « Jetons estimés » : Google ne donne pas le compte pour ce service, le site l’estime.',
            'ce mois-ci, par usage' => 'La dépense du mois répartie entre l’assistant du site, les traductions, le correcteur et l’index de l’assistant, avec le coût moyen d’un appel.',
            'comment c’est calculé' => 'Jetons consommés × tarif du modèle, converti en euros. La facture Google reste la référence.',
            'mois par mois · remboursements' => 'Pour un mois terminé : téléchargez le relevé PDF (à signer) et le détail CSV, remettez-les à l’association, puis « Noter le remboursement » une fois le virement reçu. « Annuler » le remet à rembourser.',
            'barème des modèles' => 'Les tarifs de Google en dollars par million de jetons. À mettre à jour si Google change ses prix ; une ligne datée prend effet à sa date. Les appels déjà faits ne sont jamais recalculés.',
        ],
        'utilisateurs' => [
            'screen' => 'Les membres de l’équipe : invitations, niveau d’accès, désactivation. Réservé aux administrateurs.',
            'inviter une personne' => 'La personne reçoit un lien pour choisir son mot de passe. Le lien peut aussi être copié et envoyé autrement.',
            'deux niveaux d’accès' => 'Administrateur : tout. Utilisateur : tout sauf les utilisateurs, les réglages, la suppression définitive, la restauration de versions, les sauvegardes et le lancement manuel des tâches.',
            'équipe du back-office' => 'Les comptes existants, leur niveau et leur dernière connexion.',
        ],
        'reglages' => [
            'screen' => 'Les réglages du site (l’équivalent d’un fichier de configuration) : identité, e-mail, assistant IA, traduction, dons, carte, mentions légales, cookies, sauvegardes. Les clés secrètes sont chiffrées et ne sont jamais réaffichées.',
            'adresse du site' => 'L’adresse officielle du musée (https://musee.fcsochauxretro.com), utilisée dans les e-mails, le plan du site et les partages. Sans « / » à la fin.',
            'e-mail de réception des messages' => 'Où arrivent les messages du formulaire de contact, les nouvelles contributions et l’annonce des dons.',
            'adresse affichée sur les images de partage' => 'Le texte (ex. « musee.fcsochauxretro.com ») écrit sur les images créées pour les réseaux sociaux.',
            'mot de passe d’accès au site public (pré-lancement)' => 'Tant qu’il est rempli, les visiteurs doivent le saisir pour voir le site (les membres connectés passent). Videz-le pour ouvrir le site à tous.',
            'clé api gemini' => 'La clé Google AI Studio qui fait fonctionner l’assistant, les traductions et le correcteur d’orthographe. Elle est chiffrée et n’est plus affichée une fois enregistrée.',
            'appels à gemini par jour pour la tâche de fond (plafond de coût)' => 'Nombre maximal d’appels à Gemini par jour pour la relecture de fond. Un texte déjà relu n’est jamais renvoyé : le coût ne porte que sur le nouveau.',
            'qui règle la facture google (avance de frais)' => 'La personne qui paie Google et se fait rembourser par l’association : son nom est imprimé sur le relevé mensuel (Système › Coûts IA).',
            'taux de change : 1 dollar = … euro' => 'Google facture en dollars. Reprenez le taux de votre relevé bancaire pour que les euros du relevé correspondent à ce que vous avez réellement payé.',
            'budget mensuel en euros (0 = sans limite)' => 'Une fois ce montant dépensé dans le mois, le tableau de bord vous prévient et, selon les cases ci-dessous, l’IA se met en pause jusqu’au 1er du mois suivant.',
            'consignes de l’assistant' => 'Les instructions données à l’IA (ton, limites, sources). À modifier avec prudence.',
            'questions par visiteur et par jour' => 'Limite anti-abus de l’assistant pour un même visiteur.',
            'questions par jour pour tout le site (plafond de coût)' => 'Au-delà, l’assistant fait une pause jusqu’au lendemain : la facture Gemini reste maîtrisée.',
            'mode' => '« Test » : aucun prélèvement réel (cartes de test Stripe, comptes bac à sable PayPal). Passez en « Production » une fois les vraies clés saisies et un essai réussi.',
            'objectif de la collecte (€)' => 'Le montant visé par la jauge de la page « Faire un don ».',
            'dons reçus hors ligne à ajouter à la jauge (€)' => 'Montant ajouté à la jauge en plus des dons enregistrés sur le site.',
            'stripe : secret du webhook (whsec_…)' => 'Fourni par Stripe quand vous déclarez l’adresse du webhook : il permet au site de confirmer les paiements.',
            'adresse d’expédition' => 'L’adresse qui envoie les e-mails du site ; elle doit exister chez l’hébergeur (ex. contact@fcsochauxretro.com).',
            'serveur smtp' => 'Le serveur d’envoi de l’hébergeur (voir la documentation de mise en ligne). Vide : fonction mail() de PHP.',
            'date de publication du moment n° 1' => 'Point de départ des 100 moments : un nouveau moment est révélé chaque semaine à partir de cette date.',
            'texte du bandeau cookies' => 'Le texte du bandeau de consentement (vidéos, dons) montré aux visiteurs.',
            'nombre de sauvegardes conservées' => 'Au-delà, les plus anciennes sauvegardes sont supprimées automatiquement.',
        ],
        'sauvegardes' => [
            'screen' => 'Une sauvegarde complète est faite chaque jour (données, réglages, comptes, versions…). Téléchargez-en régulièrement une pour la garder hors du serveur.',
            'restaurer' => 'Pour revenir à une sauvegarde : décompressez l’archive et remplacez les dossiers data/ et storage/ sur le serveur (gestionnaire de fichiers de l’hébergeur). Une fiche seule se restaure plus simplement depuis son onglet Historique.',
        ],
        'majs' => ['screen' => 'Nouvelle version du site sur GitHub : la liste des changements, puis « Appliquer la mise à jour » (le code seulement : jamais les fiches, médias, réglages ni comptes). Le code du serveur est aussi comparé fichier par fichier à GitHub : un fichier oublié lors d’un envoi FTP est signalé et remplacé en un clic. Une sauvegarde permet de revenir en arrière.'],
        'taches' => ['screen' => 'Les tâches automatiques (toutes les 5 minutes) : publication programmée, statistiques, traductions, newsletter, carte, sauvegarde… et leur dernier passage. « Lancer » en exécute une tout de suite.'],
        'corbeille' => ['screen' => 'Les fiches mises à la corbeille : elles ne sont plus visibles sur le site. « Sortir de la corbeille » les remet dans leur statut d’avant ; la suppression définitive est réservée aux administrateurs (une copie reste dans l’historique des versions).'],
        'profil' => [
            'screen' => 'Votre compte : nom affiché, e-mail, mot de passe et vos dernières actions dans le back-office.',
            'changer de mot de passe' => 'Au moins 10 caractères. Choisissez une phrase facile à retenir pour vous et difficile à deviner.',
            'mon activité récente' => 'Vos dernières modifications (le journal de toute l’équipe est dans Pilotage › Journal).',
        ],
        'aide' => ['screen' => 'Le guide d’utilisation complet du back-office, la recherche dans l’aide et les PDF à télécharger.'],
    ];

    /** Bulles de l'écran courant : clés en minuscules → texte (HTML simple). */
    public static function forNav(string $nav): array
    {
        $screen = self::SCREENS[$nav] ?? [];
        // L'éditeur d'un objet ou d'un moment profite aussi des bulles des fiches « articles ».
        if (in_array($nav, ['objets', 'moments'], true)) {
            $screen += array_diff_key(self::SCREENS['articles'], ['screen' => 1]);
        }
        $tips = $screen + self::COMMON;
        return \App\Core\Auth::isAdmin() ? $tips : array_map([self::class, 'withoutCosts'], $tips);
    }

    /** Coûts de l'IA (« environ 0,6 centime ») retirés : réservés aux administrateurs. */
    public static function withoutCosts(string $html): string
    {
        return (string) preg_replace('/\s*\((?:environ|soit) [^()]*?(?:centimes?|€)[^()]*\)/u', '', $html);
    }
}
