/**
 * Données de démonstration issues des maquettes : territoire pilote du Val de Loue.
 * Les photos proviennent d'Unsplash (démonstration uniquement : en production, la charte
 * impose des photos réelles des professionnels du territoire).
 */
import type { Family } from '@/lib/constants';

export const U = (id: string, w = 800, h?: number) =>
  `https://images.unsplash.com/photo-${id}?w=${w}${h ? `&h=${h}` : ''}&fit=crop&q=70&auto=format`;

export const I = {
  bread: '1509440159596-0249088772ff',
  crois: '1555507036-ab1f4038808a',
  bakery: '1517433670267-08bbd4be890f',
  cheese: '1486297678162-eb2a19b0a32d',
  board: '1452195100486-9cc805987862',
  resto: '1517248135467-4c7edcad34c4',
  plate: '1414235077428-338989a2e8c0',
  food: '1504674900247-0877df9cc836',
  drill: '1504148455328-c376907d081c',
  toast: '1510812431401-41d2bd2722f3',
  vine: '1506377247377-2a5b3b417ebb',
  veg: '1488459716781-31db52582fe9',
  grocery: '1542838132-92c53300491e',
  vases: '1565193566173-7a0ee3dbe261',
  pottery: '1493106641515-6b5631de4bb9',
  cook: '1556910103-1c02745aae4d',
  workshop: '1581091226825-a6a2a5aee158',
  elec: '1621905251189-08b45d6a269e',
  plumb: '1585704032915-c3400ca199e7',
  store: '1441986300917-64674bd600d8',
  market: '1533900298318-6b8da08a523e',
  carrots: '1464226184884-fa280b87c399',
  choco: '1549007994-cb92caebd54b',
  crowd: '1528605248644-14dd04022da1',
  terrace: '1559339352-11d035aa65de',
  field: '1605000797499-95a51c5269ae',
  crafts: '1452860606245-08befc0ff44b',
  board2: '1466637574441-749b8f19452f',
  forest: '1441974231531-c6227db76b6e',
  xmas: '1543589077-47d81606c1bf',
  xmas2: '1512389142860-9c449e58a543',
  team: '1522071820081-009f0129c71c',
  valley: '1470071459604-3b5ec3a7fe05',
  mountains: '1506905925346-21bda4d32df4',
  p1: '1500648767791-00dcc994a43e',
  p2: '1494790108377-be9c29b29330',
  p3: '1507003211169-0a1dd7228f2d',
  p4: '1438761681033-6461ffad8d80',
} as const;

// ─── Référentiel des catégories (taxonomie de la plateforme) ────────────────
export type CategorySeed = { slug: string; name: string; family: Family; naf: string[]; synonyms: string[]; img: string };

export const CATEGORIES: CategorySeed[] = [
  { slug: 'boulangerie', name: 'Boulangerie', family: 'ARTISAN', naf: ['10.71C', '10.71D'], synonyms: ['pain', 'levain', 'viennoiserie', 'croissant', 'pâtisserie', 'boulanger'], img: I.bread },
  { slug: 'fromagerie', name: 'Fromagerie', family: 'PRODUCTEUR', naf: ['10.51C', '47.29Z'], synonyms: ['fromage', 'comté', 'crèmerie', 'fruitière'], img: I.cheese },
  { slug: 'restaurant', name: 'Restaurant', family: 'RESTAURATION', naf: ['56.10A'], synonyms: ['restaurant', 'cuisine', 'dîner', 'déjeuner', 'table'], img: I.resto },
  { slug: 'menuiserie', name: 'Menuiserie', family: 'ARTISAN', naf: ['16.23Z', '43.32A'], synonyms: ['menuisier', 'bois', 'escalier', 'fenêtre', 'agencement'], img: I.drill },
  { slug: 'plombier-chauffagiste', name: 'Plombier chauffagiste', family: 'SERVICES', naf: ['43.22A', '43.22B'], synonyms: ['plombier', 'chauffagiste', 'chaudière', 'chauffage', 'fuite', 'plomberie', 'pompe à chaleur', 'dépannage'], img: I.plumb },
  { slug: 'caviste', name: 'Caviste', family: 'COMMERCE', naf: ['47.25Z'], synonyms: ['vin', 'cave', 'spiritueux', 'bière', 'whisky'], img: I.vine },
  { slug: 'maraicher', name: 'Maraîcher', family: 'PRODUCTEUR', naf: ['01.13Z'], synonyms: ['légumes', 'maraîchage', 'panier', 'fruits'], img: I.veg },
  { slug: 'metiers-d-art', name: "Métiers d'art", family: 'ARTISAN', naf: ['23.41Z', '90.03A'], synonyms: ['céramique', 'poterie', 'céramiste', 'verrier', 'artisan d’art'], img: I.pottery },
  { slug: 'chocolatier', name: 'Chocolatier', family: 'COMMERCE', naf: ['10.82Z'], synonyms: ['chocolat', 'confiserie', 'bonbons', 'pralines'], img: I.choco },
  { slug: 'auberge', name: 'Auberge', family: 'RESTAURATION', naf: ['55.10Z'], synonyms: ['auberge', 'table d’hôtes', 'terroir'], img: I.plate },
  { slug: 'apiculteur', name: 'Apiculteur', family: 'PRODUCTEUR', naf: ['01.49Z'], synonyms: ['miel', 'ruche', 'cire', 'abeille'], img: I.board2 },
  { slug: 'garage', name: 'Garage', family: 'SERVICES', naf: ['45.20A', '45.20B'], synonyms: ['mécanique', 'voiture', 'garagiste', 'carrosserie', 'pneus', 'vidange'], img: I.workshop },
  { slug: 'epicerie', name: 'Épicerie', family: 'COMMERCE', naf: ['47.11B', '47.29Z'], synonyms: ['épicerie', 'vrac', 'alimentation', 'zéro déchet', 'produits fins'], img: I.grocery },
  { slug: 'distillerie', name: 'Distillerie', family: 'PRODUCTEUR', naf: ['11.01Z'], synonyms: ['absinthe', 'eau-de-vie', 'liqueur', 'gentiane'], img: I.toast },
  { slug: 'bistrot', name: 'Bistrot', family: 'RESTAURATION', naf: ['56.30Z'], synonyms: ['bistrot', 'brasserie', 'café', 'bar'], img: I.food },
  { slug: 'ebeniste', name: 'Ébéniste', family: 'ARTISAN', naf: ['31.09B'], synonyms: ['meuble', 'ébénisterie', 'marqueterie', 'restauration de meubles'], img: I.vases },
  { slug: 'boucherie', name: 'Boucherie-charcuterie', family: 'COMMERCE', naf: ['47.22Z', '10.13B'], synonyms: ['viande', 'charcuterie', 'boucher', 'saucisse de Morteau'], img: I.board },
  { slug: 'coiffure', name: 'Coiffure', family: 'SERVICES', naf: ['96.02A'], synonyms: ['coiffeur', 'coiffeuse', 'barbier', 'salon'], img: I.store },
  { slug: 'institut-beaute', name: 'Institut de beauté', family: 'SERVICES', naf: ['96.02B'], synonyms: ['esthétique', 'soins', 'manucure', 'massage'], img: I.store },
  { slug: 'pharmacie', name: 'Pharmacie', family: 'COMMERCE', naf: ['47.73Z'], synonyms: ['pharmacien', 'parapharmacie', 'médicaments'], img: I.store },
  { slug: 'fleuriste', name: 'Fleuriste', family: 'COMMERCE', naf: ['47.76Z'], synonyms: ['fleurs', 'bouquet', 'plantes'], img: I.crafts },
  { slug: 'librairie', name: 'Librairie-presse', family: 'COMMERCE', naf: ['47.61Z', '47.62Z'], synonyms: ['livres', 'journaux', 'papeterie', 'bd'], img: I.store },
  { slug: 'electricien', name: 'Électricien', family: 'SERVICES', naf: ['43.21A'], synonyms: ['électricité', 'éclairage', 'domotique', 'dépannage électrique'], img: I.elec },
  { slug: 'maconnerie', name: 'Maçonnerie', family: 'ARTISAN', naf: ['43.99C'], synonyms: ['maçon', 'rénovation', 'pierre', 'construction'], img: I.workshop },
  { slug: 'couvreur', name: 'Couvreur', family: 'ARTISAN', naf: ['43.91B'], synonyms: ['toiture', 'zinguerie', 'charpente'], img: I.workshop },
  { slug: 'peintre', name: 'Peintre en bâtiment', family: 'ARTISAN', naf: ['43.34Z'], synonyms: ['peinture', 'décoration', 'papier peint'], img: I.workshop },
  { slug: 'ferme', name: 'Ferme & élevage', family: 'PRODUCTEUR', naf: ['01.41Z', '01.45Z'], synonyms: ['viande', 'élevage', 'vente à la ferme', 'lait', 'œufs'], img: I.field },
  { slug: 'brasserie-artisanale', name: 'Brasserie artisanale', family: 'PRODUCTEUR', naf: ['11.05Z'], synonyms: ['bière', 'brasseur', 'houblon'], img: I.toast },
  { slug: 'pizzeria', name: 'Pizzeria', family: 'RESTAURATION', naf: ['56.10C'], synonyms: ['pizza', 'à emporter', 'italien'], img: I.food },
  { slug: 'traiteur', name: 'Traiteur', family: 'RESTAURATION', naf: ['56.21Z'], synonyms: ['traiteur', 'buffet', 'plats cuisinés', 'réception'], img: I.cook },
  { slug: 'hebergement', name: 'Hôtel & gîte', family: 'SERVICES', naf: ['55.10Z', '55.20Z'], synonyms: ['hôtel', 'gîte', 'chambre d’hôtes', 'hébergement', 'dormir'], img: I.mountains },
  { slug: 'superette', name: 'Supérette', family: 'COMMERCE', naf: ['47.11B', '47.11C'], synonyms: ['alimentation', 'courses', 'supermarché'], img: I.grocery },
  { slug: 'pret-a-porter', name: 'Prêt-à-porter', family: 'COMMERCE', naf: ['47.71Z'], synonyms: ['vêtements', 'mode', 'boutique', 'chaussures'], img: I.store },
  { slug: 'informatique', name: 'Informatique', family: 'SERVICES', naf: ['95.11Z', '62.02A'], synonyms: ['ordinateur', 'dépannage informatique', 'réparation téléphone'], img: I.elec },
  { slug: 'taxi', name: 'Taxi', family: 'SERVICES', naf: ['49.32Z'], synonyms: ['taxi', 'transport', 'navette'], img: I.workshop },
  { slug: 'conseil', name: 'Conseil & expertise', family: 'SERVICES', naf: ['69.20Z', '71.11Z', '70.22Z'], synonyms: ['comptable', 'architecte', 'conseil', 'assurance'], img: I.team },
  { slug: 'cordonnerie', name: 'Cordonnerie', family: 'ARTISAN', naf: ['95.23Z'], synonyms: ['cordonnier', 'clés', 'chaussures', 'réparation'], img: I.crafts },
  { slug: 'paysagiste', name: 'Paysagiste', family: 'SERVICES', naf: ['81.30Z'], synonyms: ['jardin', 'espaces verts', 'élagage', 'tonte'], img: I.forest },
  { slug: 'auto-ecole', name: 'Auto-école', family: 'SERVICES', naf: ['85.53Z'], synonyms: ['permis', 'conduite'], img: I.workshop },
  { slug: 'bricolage', name: 'Quincaillerie & bricolage', family: 'COMMERCE', naf: ['47.52A', '47.52B'], synonyms: ['bricolage', 'outils', 'quincaillerie', 'jardinage'], img: I.drill },
  { slug: 'opticien', name: 'Opticien', family: 'COMMERCE', naf: ['47.78A'], synonyms: ['lunettes', 'optique', 'lentilles'], img: I.store },
  { slug: 'tabac-presse', name: 'Tabac-presse', family: 'COMMERCE', naf: ['47.26Z'], synonyms: ['tabac', 'presse', 'loto', 'journaux'], img: I.store },
];

export type AttributeSeed = { slug: string; label: string; group: 'SERVICE' | 'PAYMENT' | 'ACCESSIBILITY' | 'LABEL' | 'HIGHLIGHT'; isFilter?: boolean };

export const ATTRIBUTES: AttributeSeed[] = [
  { slug: 'fabrication-locale', label: 'Fabrication locale', group: 'HIGHLIGHT', isFilter: true },
  { slug: 'idees-cadeaux', label: 'Idées cadeaux', group: 'HIGHLIGHT', isFilter: true },
  { slug: 'click-collect', label: 'Click & collect', group: 'SERVICE', isFilter: true },
  { slug: 'livraison', label: 'Livraison', group: 'SERVICE', isFilter: true },
  { slug: 'rdv-en-ligne', label: 'RDV en ligne', group: 'SERVICE', isFilter: true },
  { slug: 'vente-directe', label: 'Vente directe', group: 'SERVICE' },
  { slug: 'terrasse', label: 'Terrasse', group: 'SERVICE' },
  { slug: 'sur-devis', label: 'Sur devis', group: 'SERVICE' },
  { slug: 'visite', label: 'Visite', group: 'SERVICE' },
  { slug: 'depannage-chaudiere', label: 'Dépannage chaudière', group: 'SERVICE' },
  { slug: 'produits-locaux', label: 'Produits locaux', group: 'HIGHLIGHT' },
  { slug: 'zero-dechet', label: 'Zéro déchet', group: 'HIGHLIGHT' },
  { slug: 'sans-gluten', label: 'Sans gluten', group: 'HIGHLIGHT' },
  { slug: 'bio', label: 'Bio', group: 'LABEL', isFilter: true },
  { slug: 'aop-comte', label: 'AOP Comté', group: 'LABEL' },
  { slug: 'rge', label: 'RGE', group: 'LABEL' },
  { slug: 'artisan-boulanger', label: 'Artisan boulanger', group: 'LABEL' },
  { slug: 'maitre-restaurateur', label: 'Maître restaurateur', group: 'LABEL' },
  { slug: 'epv', label: 'Entreprise du patrimoine vivant', group: 'LABEL' },
  { slug: 'acces-pmr', label: 'Accès PMR', group: 'ACCESSIBILITY', isFilter: true },
  { slug: 'boucle-magnetique', label: 'Boucle magnétique', group: 'ACCESSIBILITY' },
  { slug: 'carte-bancaire', label: 'Carte bancaire', group: 'PAYMENT' },
  { slug: 'especes', label: 'Espèces', group: 'PAYMENT' },
  { slug: 'cheque', label: 'Chèque', group: 'PAYMENT' },
  { slug: 'sans-contact', label: 'Sans contact', group: 'PAYMENT' },
  { slug: 'tickets-resto', label: 'Tickets resto', group: 'PAYMENT' },
  { slug: 'cheques-vacances', label: 'Chèques vacances', group: 'PAYMENT' },
];

// ─── Communes du Val de Loue (24) ───────────────────────────────────────────
export type CommuneSeed = {
  insee: string;
  name: string;
  postal: string;
  pop: number;
  lat: number;
  lng: number;
  /** Nombre d'établissements référencés (densité de la maquette) */
  count: number;
  /** Taux de revendication visé (%) */
  claimRate: number;
};

export const VAL_DE_LOUE_COMMUNES: CommuneSeed[] = [
  { insee: '25434', name: 'Ornans', postal: '25290', pop: 4330, lat: 47.1062, lng: 6.1446, count: 214, claimRate: 71 },
  { insee: '25475', name: 'Quingey', postal: '25440', pop: 1420, lat: 47.1027, lng: 5.8836, count: 96, claimRate: 58 },
  { insee: '25013', name: 'Amancey', postal: '25330', pop: 720, lat: 47.0406, lng: 6.0747, count: 58, claimRate: 44 },
  { insee: '25632', name: 'Vuillafans', postal: '25840', pop: 760, lat: 47.0775, lng: 6.1978, count: 41, claimRate: 52 },
  { insee: '25411', name: 'Mouthier-Haute-Pierre', postal: '25920', pop: 380, lat: 47.0386, lng: 6.2786, count: 33, claimRate: 64 },
  { insee: '25339', name: 'Lods', postal: '25930', pop: 250, lat: 47.0497, lng: 6.2372, count: 22, claimRate: 36 },
  { insee: '25389', name: 'Montgesoye', postal: '25111', pop: 470, lat: 47.0885, lng: 6.1885, count: 27, claimRate: 29 },
  { insee: '25418', name: 'Nans-sous-Sainte-Anne', postal: '25330', pop: 130, lat: 46.9786, lng: 6.0019, count: 14, claimRate: 36 },
  { insee: '25155', name: 'Cléron', postal: '25330', pop: 330, lat: 47.0886, lng: 6.0661, count: 19, claimRate: 32 },
  { insee: '25147', name: 'Chenecey-Buillon', postal: '25440', pop: 480, lat: 47.1325, lng: 5.9591, count: 24, claimRate: 33 },
  { insee: '25116', name: 'Chantrans', postal: '25330', pop: 310, lat: 47.0428, lng: 6.1531, count: 17, claimRate: 29 },
  { insee: '25537', name: 'Scey-Maisières', postal: '25290', pop: 330, lat: 47.1028, lng: 6.0964, count: 21, claimRate: 38 },
  { insee: '25206', name: 'Durnes', postal: '25580', pop: 190, lat: 47.0726, lng: 6.2459, count: 16, claimRate: 22 },
  { insee: '25212', name: 'Échevannes', postal: '25580', pop: 150, lat: 47.0689, lng: 6.2825, count: 12, claimRate: 25 },
  { insee: '25361', name: 'Malbrans', postal: '25620', pop: 180, lat: 47.0829, lng: 6.0386, count: 14, claimRate: 25 },
  { insee: '25104', name: 'Cademène', postal: '25290', pop: 70, lat: 47.1193, lng: 6.0405, count: 9, claimRate: 20 },
  { insee: '25338', name: 'Lizine', postal: '25330', pop: 60, lat: 47.0731, lng: 5.9859, count: 8, claimRate: 20 },
  { insee: '25128', name: 'Charnay', postal: '25440', pop: 330, lat: 47.1413, lng: 5.9308, count: 22, claimRate: 29 },
  { insee: '25217', name: 'Épeugney', postal: '25290', pop: 560, lat: 47.1275, lng: 6.0239, count: 28, claimRate: 33 },
  { insee: '25556', name: 'Tarcenay-Foucherans', postal: '25620', pop: 1100, lat: 47.1622, lng: 6.1127, count: 62, claimRate: 42 },
  { insee: '25069', name: 'Bolandoz', postal: '25330', pop: 330, lat: 46.9975, lng: 6.1156, count: 18, claimRate: 27 },
  { insee: '25533', name: 'Saraz', postal: '25330', pop: 20, lat: 47.0292, lng: 5.9833, count: 7, claimRate: 33 },
  { insee: '25544', name: 'Silley-Amancey', postal: '25330', pop: 110, lat: 47.0214, lng: 6.0572, count: 11, claimRate: 17 },
  { insee: '25237', name: 'Flagey', postal: '25330', pop: 200, lat: 47.0339, lng: 6.1097, count: 20, claimRate: 30 },
];

// ─── Les 16 établissements détaillés des maquettes ──────────────────────────
export type Slot = [number, string, string]; // weekday, opens, closes

export type EstablishmentSeed = {
  key: string;
  name: string;
  category: string;
  activity: string;
  commune: string;
  lat: number;
  lng: number;
  street: string;
  phone: string;
  email?: string;
  website?: string;
  cover: string;
  gallery?: [string, string | null][];
  tagline?: string;
  description: string;
  attrs: string[];
  hours: Slot[];
  status: 'PRECREATED' | 'TO_COMPLETE' | 'CLAIMED' | 'VALIDATED' | 'SUSPENDED';
  plan: 'ESSENTIEL' | 'PREMIUM' | 'COMMUNICATION';
  owner?: { first: string; last: string; email: string };
  siret: string;
  legalName: string;
  products?: [string, string, string][];
  updatedDaysAgo: number;
};

const weekdays = (from: number, to: number, opens: string, closes: string): Slot[] =>
  Array.from({ length: to - from + 1 }, (_, i) => [from + i, opens, closes] as Slot);

export const ESTABLISHMENTS: EstablishmentSeed[] = [
  {
    key: 'b1',
    name: 'Boulangerie Martin',
    category: 'boulangerie',
    activity: 'Boulangerie',
    commune: 'Ornans',
    lat: 47.1068,
    lng: 6.1432,
    street: '12 rue Pierre Vernier',
    phone: '0381621407',
    email: 'sophie@boulangerie-martin.fr',
    cover: I.bread,
    gallery: [
      [I.bread, 'Principale'],
      [I.crois, null],
      [I.bakery, null],
      [I.board2, null],
      [I.cook, 'Équipe'],
      [I.store, null],
    ],
    tagline: 'Pains au levain naturel et galettes comtoises',
    description:
      'Depuis 1987, la famille Martin pétrit chaque nuit des pains au levain naturel avec les farines du moulin de Vuillafans. Viennoiseries au beurre AOP, galettes comtoises et, le samedi, cuisson au feu de bois.',
    attrs: ['fabrication-locale', 'click-collect', 'idees-cadeaux', 'carte-bancaire', 'especes', 'cheque', 'acces-pmr', 'artisan-boulanger'],
    hours: [...weekdays(1, 4, '06:30', '19:00'), [5, '06:30', '18:00'], [6, '07:00', '12:30']],
    status: 'VALIDATED',
    plan: 'ESSENTIEL',
    owner: { first: 'Sophie', last: 'Martin', email: 'sophie@boulangerie-martin.fr' },
    siret: '81234567800019',
    legalName: 'MARTIN SOPHIE',
    products: [
      ['Pain de campagne au levain', '4,20 € / kg', I.bread],
      ['Croissant pur beurre AOP', '1,30 €', I.crois],
      ['Galette comtoise', 'Sur commande · 18 €', I.bakery],
      ['Planche apéro du samedi', '9,50 €', I.board2],
    ],
    updatedDaysAgo: 2,
  },
  {
    key: 'b2',
    name: 'Fromagerie du Plateau',
    category: 'fromagerie',
    activity: 'Fromagerie',
    commune: 'Amancey',
    lat: 47.0412,
    lng: 6.0738,
    street: 'Route de Salins',
    phone: '0381864210',
    email: 'contact@fromagerie-plateau.fr',
    website: 'https://fromagerie-plateau.fr',
    cover: I.cheese,
    gallery: [
      [I.cheese, 'Principale'],
      [I.board, null],
      [I.board2, 'Intérieur'],
      [I.field, null],
      [I.store, 'Intérieur'],
    ],
    tagline: 'Comté affiné sur place, de 12 à 36 mois',
    description:
      "Coopérative fromagère du plateau d'Amancey : le lait de 18 fermes voisines devient chaque jour du Comté AOP, affiné dans nos caves de 12 à 36 mois. Boutique ouverte au public, dégustation commentée le vendredi et coffrets à offrir toute l'année. Nous proposons aussi le Morbier, la cancoillotte maison et une sélection de vins du Jura pour accompagner le plateau.",
    attrs: ['vente-directe', 'aop-comte', 'idees-cadeaux', 'carte-bancaire', 'especes', 'acces-pmr', 'fabrication-locale'],
    hours: [...weekdays(1, 5, '09:00', '12:30'), ...weekdays(1, 5, '14:30', '18:30'), [6, '09:30', '12:00']],
    status: 'VALIDATED',
    plan: 'PREMIUM',
    owner: { first: 'Bruno', last: 'Cuenot', email: 'bruno@fromagerie-plateau.fr' },
    siret: '42198765400027',
    legalName: 'FROMAGERIE DU PLATEAU SCA',
    products: [
      ['Comté AOP 18 mois', '24,90 € / kg', I.cheese],
      ['Coffret « Plateau comtois »', '39 €', I.board],
      ['Cancoillotte maison', '4,80 €', I.board2],
    ],
    updatedDaysAgo: 5,
  },
  {
    key: 'b3',
    name: 'Le Relais de la Loue',
    category: 'restaurant',
    activity: 'Restaurant',
    commune: 'Vuillafans',
    lat: 47.0778,
    lng: 6.2003,
    street: '2 place du Pont',
    phone: '0381598812',
    email: 'reservation@relais-loue.fr',
    website: 'https://relais-loue.fr',
    cover: I.terrace,
    gallery: [
      [I.terrace, 'Principale'],
      [I.plate, null],
      [I.resto, 'Intérieur'],
      [I.food, null],
      [I.valley, null],
    ],
    tagline: 'Truite de la Loue et cuisine de saison, terrasse sur la rivière',
    description:
      "Au bord de la Loue, le Relais accueille jusqu'à 80 couverts en terrasse l'été. Cuisine de produits locaux : truite de la Loue au vin jaune, morilles, Comté du plateau et desserts maison. Menu du jour le midi en semaine, carte le soir et le week-end. Réservation conseillée le samedi soir et les jours fériés ; groupes et repas de famille sur demande.",
    attrs: ['terrasse', 'produits-locaux', 'carte-bancaire', 'especes', 'tickets-resto', 'cheques-vacances', 'acces-pmr', 'maitre-restaurateur'],
    hours: [...weekdays(1, 6, '12:00', '14:00'), ...weekdays(1, 6, '19:00', '22:30')],
    status: 'VALIDATED',
    plan: 'PREMIUM',
    owner: { first: 'Nicolas', last: 'Bourgeois', email: 'nicolas@relais-loue.fr' },
    siret: '53421987600015',
    legalName: 'SARL LE RELAIS DE LA LOUE',
    products: [
      ['Truite de la Loue au vin jaune', '22 €', I.plate],
      ['Menu du jour', '16,50 €', I.food],
      ['Assiette comtoise', '18 €', I.board],
    ],
    updatedDaysAgo: 1,
  },
  {
    key: 'b4',
    name: 'Atelier Bois Girard',
    category: 'menuiserie',
    activity: 'Menuiserie',
    commune: 'Quingey',
    lat: 47.1021,
    lng: 5.8851,
    street: 'ZA des Prés',
    phone: '0381635544',
    cover: I.drill,
    tagline: 'Escaliers, agencements et fenêtres sur mesure',
    description: 'Menuiserie traditionnelle à Quingey : escaliers, agencements, fenêtres bois sur mesure.',
    attrs: ['fabrication-locale', 'sur-devis'],
    hours: [...weekdays(0, 4, '08:00', '12:00'), ...weekdays(0, 4, '13:30', '18:00')],
    status: 'CLAIMED',
    plan: 'ESSENTIEL',
    owner: { first: 'Thierry', last: 'Girard', email: 'contact@atelier-girard.fr' },
    siret: '38765432100021',
    legalName: 'GIRARD THIERRY',
    updatedDaysAgo: 21,
  },
  {
    key: 'b5',
    name: 'Chauffage Mougin',
    category: 'plombier-chauffagiste',
    activity: 'Plombier chauffagiste',
    commune: 'Ornans',
    lat: 47.1049,
    lng: 6.1478,
    street: '8 avenue du Président Wilson',
    phone: '0381570366',
    website: 'https://chauffage-mougin.fr',
    cover: I.plumb,
    tagline: 'Dépannage de chaudières 7j/7, pompes à chaleur',
    description: "Chauffagiste certifié RGE : installation et entretien de chaudières et pompes à chaleur, dépannage 7j/7 sur tout le Val de Loue.",
    attrs: ['depannage-chaudiere', 'rge', 'sur-devis'],
    hours: [...weekdays(0, 4, '08:00', '12:00'), ...weekdays(0, 4, '13:30', '18:00'), [5, '09:00', '12:00']],
    status: 'PRECREATED',
    plan: 'ESSENTIEL',
    siret: '79012345600018',
    legalName: 'MOUGIN JULIEN',
    updatedDaysAgo: 190,
  },
  {
    key: 'b6',
    name: 'La Cave Comtoise',
    category: 'caviste',
    activity: 'Caviste',
    commune: 'Ornans',
    lat: 47.1076,
    lng: 6.1463,
    street: '5 rue Saint-Laurent',
    phone: '0381620099',
    email: 'bonjour@cave-comtoise.fr',
    website: 'https://cave-comtoise.fr',
    cover: I.vine,
    gallery: [
      [I.vine, 'Principale'],
      [I.toast, null],
      [I.store, 'Intérieur'],
      [I.board, null],
      [I.crowd, 'Intérieur'],
    ],
    tagline: 'Vins du Jura, spiritueux comtois et coffrets',
    description:
      "Cave indépendante au cœur d'Ornans : plus de 400 références, dont 120 vins du Jura (savagnin, vin jaune, crémant), des spiritueux de la vallée et une belle sélection de bières artisanales. Dégustations le samedi, coffrets personnalisés pour les particuliers et les entreprises, commande en click & collect et livraison dans le Val de Loue.",
    attrs: ['click-collect', 'idees-cadeaux', 'livraison', 'carte-bancaire', 'especes', 'sans-contact', 'acces-pmr'],
    hours: [...weekdays(1, 5, '09:30', '12:30'), ...weekdays(1, 5, '14:30', '19:30'), [6, '10:00', '12:30']],
    status: 'VALIDATED',
    plan: 'COMMUNICATION',
    owner: { first: 'Julie', last: 'Faivre', email: 'julie@cave-comtoise.fr' },
    siret: '84512398700014',
    legalName: 'LA CAVE COMTOISE SAS',
    products: [
      ['Vin jaune « Château-Chalon »', '42 €', I.vine],
      ['Crémant du Jura', '12,50 €', I.toast],
      ['Coffret dégustation 3 vins', '35 €', I.board],
    ],
    updatedDaysAgo: 1,
  },
  {
    key: 'b7',
    name: 'Ferme des Granges',
    category: 'maraicher',
    activity: 'Maraîcher bio',
    commune: 'Quingey',
    lat: 47.0985,
    lng: 5.8905,
    street: 'Les Granges',
    phone: '0381635912',
    cover: I.veg,
    tagline: 'Légumes bio et paniers hebdomadaires',
    description: 'Ferme maraîchère bio de 3 hectares, vente directe et paniers hebdomadaires pour 120 familles.',
    attrs: ['bio', 'vente-directe'],
    hours: [[2, '16:00', '19:00'], [5, '09:00', '12:00']],
    status: 'TO_COMPLETE',
    plan: 'ESSENTIEL',
    owner: { first: 'Émilie', last: 'Granges', email: 'ferme.granges@exemple.test' },
    siret: '82345678900011',
    legalName: 'EARL DES GRANGES',
    updatedDaysAgo: 62,
  },
  {
    key: 'b8',
    name: 'Céramiques Lison',
    category: 'metiers-d-art',
    activity: "Métiers d'art",
    commune: 'Nans-sous-Sainte-Anne',
    lat: 46.9786,
    lng: 6.0019,
    street: 'Rue de la Source',
    phone: '0381864477',
    cover: I.pottery,
    tagline: 'Céramiques tournées à la main, pièces uniques',
    description: "Atelier de céramique au pied de la source du Lison : grès et porcelaine tournés à la main, cuissons raku.",
    attrs: ['fabrication-locale', 'idees-cadeaux'],
    hours: [...weekdays(2, 6, '14:00', '18:00')],
    status: 'SUSPENDED',
    plan: 'ESSENTIEL',
    owner: { first: 'Clara', last: 'Lison', email: 'clara@ceramiques-lison.fr' },
    siret: '87654321000019',
    legalName: 'LISON CLARA',
    updatedDaysAgo: 150,
  },
  {
    key: 'b9',
    name: 'Chocolaterie Vuillemin',
    category: 'chocolatier',
    activity: 'Chocolatier',
    commune: 'Ornans',
    lat: 47.1058,
    lng: 6.1418,
    street: '3 Grande Rue',
    phone: '0381621830',
    email: 'boutique@chocolaterie-vuillemin.fr',
    website: 'https://chocolaterie-vuillemin.fr',
    cover: I.choco,
    gallery: [
      [I.choco, 'Principale'],
      [I.store, 'Intérieur'],
      [I.crafts, null],
      [I.board2, null],
      [I.cook, 'Équipe'],
    ],
    tagline: 'Chocolats fins et coffret « Loue gourmande »',
    description:
      "Maison artisanale fondée par Pierre Vuillemin : ganaches aux herbes des monts du Jura, pralinés à l'ancienne et le fameux « galet de la Loue ». Tout est fabriqué dans notre laboratoire derrière la boutique, avec un chocolat de couverture issu du commerce équitable. Coffrets sur mesure pour les entreprises et les fêtes, envoi partout en France.",
    attrs: ['fabrication-locale', 'idees-cadeaux', 'click-collect', 'carte-bancaire', 'especes', 'acces-pmr'],
    hours: [...weekdays(1, 5, '09:00', '19:00'), [6, '09:00', '12:30']],
    status: 'VALIDATED',
    plan: 'PREMIUM',
    owner: { first: 'Pierre', last: 'Vuillemin', email: 'pierre@chocolaterie-vuillemin.fr' },
    siret: '51234987600013',
    legalName: 'CHOCOLATERIE VUILLEMIN SARL',
    products: [
      ['Coffret « Loue gourmande »', '28 €', I.choco],
      ['Galets de la Loue (250 g)', '14,50 €', I.crafts],
      ['Tablette noire 70 %', '6,20 €', I.board2],
    ],
    updatedDaysAgo: 0,
  },
  {
    key: 'b10',
    name: 'Auberge du Moulin',
    category: 'auberge',
    activity: 'Auberge',
    commune: 'Mouthier-Haute-Pierre',
    lat: 47.0386,
    lng: 6.278,
    street: 'Route des gorges de Nouailles',
    phone: '0381609218',
    cover: I.plate,
    tagline: 'Cuisine de terroir, produits à moins de 30 km',
    description: 'Auberge de 40 couverts, cuisine de terroir revisitée avec des produits des fermes voisines.',
    attrs: ['produits-locaux', 'terrasse', 'carte-bancaire'],
    hours: [...weekdays(2, 6, '12:00', '14:00'), ...weekdays(2, 6, '19:00', '22:00')],
    status: 'CLAIMED',
    plan: 'ESSENTIEL',
    owner: { first: 'Marc', last: 'Jeunet', email: 'auberge.moulin@exemple.test' },
    siret: '44556677800012',
    legalName: 'AUBERGE DU MOULIN EURL',
    updatedDaysAgo: 7,
  },
  {
    key: 'b11',
    name: 'Miellerie des Côtes',
    category: 'apiculteur',
    activity: 'Apiculteur',
    commune: 'Lods',
    lat: 47.0493,
    lng: 6.236,
    street: 'Chemin des ruchers',
    phone: '0381602741',
    cover: I.board2,
    tagline: 'Miel de sapin et de montagne',
    description: 'Apiculteurs sur les côtes de la Loue : miel de sapin, de montagne et de printemps.',
    attrs: ['vente-directe', 'idees-cadeaux'],
    hours: [[5, '10:00', '12:00'], [5, '14:00', '18:00']],
    status: 'TO_COMPLETE',
    plan: 'ESSENTIEL',
    siret: '90123456700015',
    legalName: 'BOUVIER LEA',
    updatedDaysAgo: 120,
  },
  {
    key: 'b12',
    name: 'Garage des Tilleuls',
    category: 'garage',
    activity: 'Garage',
    commune: 'Montgesoye',
    lat: 47.088,
    lng: 6.188,
    street: '2 route de Besançon',
    phone: '0381570912',
    cover: I.workshop,
    tagline: 'Mécanique toutes marques',
    description: 'Garage toutes marques : entretien, pneus, contrôle technique préparé.',
    attrs: ['rdv-en-ligne'],
    hours: [...weekdays(0, 4, '08:00', '12:00'), ...weekdays(0, 4, '14:00', '18:30'), [5, '08:00', '12:00']],
    status: 'PRECREATED',
    plan: 'ESSENTIEL',
    siret: '31234567800017',
    legalName: 'SARL GARAGE DES TILLEULS',
    updatedDaysAgo: 190,
  },
  {
    key: 'b13',
    name: 'Épicerie Vrac & Co',
    category: 'epicerie',
    activity: 'Épicerie vrac',
    commune: 'Quingey',
    lat: 47.103,
    lng: 5.8822,
    street: '14 rue de la Mairie',
    phone: '0381635170',
    email: 'hello@vracetco.fr',
    website: 'https://vracetco.fr',
    cover: I.grocery,
    gallery: [
      [I.grocery, 'Principale'],
      [I.store, 'Intérieur'],
      [I.veg, null],
      [I.carrots, null],
      [I.board2, null],
    ],
    tagline: 'Épicerie vrac, locale et zéro déchet',
    description:
      "À Quingey, une épicerie sans emballage : céréales, légumineuses, huiles, produits d'entretien et cosmétiques solides, à la pesée. La moitié des références vient de moins de 50 km, dont les légumes de la Ferme des Granges et le miel des Côtes. Apportez vos contenants, ou empruntez nos bocaux consignés. Commande en ligne et retrait en boutique.",
    attrs: ['zero-dechet', 'click-collect', 'produits-locaux', 'bio', 'carte-bancaire', 'especes', 'acces-pmr'],
    hours: [...weekdays(1, 5, '09:00', '13:00'), ...weekdays(1, 5, '15:00', '19:00'), [6, '09:30', '12:30']],
    status: 'VALIDATED',
    plan: 'PREMIUM',
    owner: { first: 'Inès', last: 'Roy', email: 'ines@vracetco.fr' },
    siret: '85012345600018',
    legalName: 'VRAC ET CO SAS',
    products: [
      ['Panier découverte zéro déchet', '25 €', I.grocery],
      ['Lentilles vertes du Jura (1 kg)', '5,40 €', I.carrots],
      ['Savon solide à la gentiane', '6 €', I.store],
    ],
    updatedDaysAgo: 3,
  },
  {
    key: 'b14',
    name: 'Distillerie du Val',
    category: 'distillerie',
    activity: 'Distillerie',
    commune: 'Mouthier-Haute-Pierre',
    lat: 47.0398,
    lng: 6.2762,
    street: 'Place de l’Église',
    phone: '0381609033',
    email: 'visites@distillerie-du-val.fr',
    website: 'https://distillerie-du-val.fr',
    cover: I.toast,
    gallery: [
      [I.toast, 'Principale'],
      [I.vine, null],
      [I.workshop, 'Intérieur'],
      [I.forest, null],
      [I.team, 'Équipe'],
    ],
    tagline: 'Absinthe et eaux-de-vie de la vallée depuis 1920',
    description:
      "Distillerie familiale depuis 1920 à Mouthier-Haute-Pierre, berceau de la cerise du même nom. Alambics en cuivre, absinthe distillée selon la recette de l'arrière-grand-père, eaux-de-vie de kirsch, de gentiane et de poire. Visites commentées de l'atelier avec dégustation, boutique ouverte du lundi au samedi et expédition des commandes en 48 h.",
    attrs: ['visite', 'idees-cadeaux', 'fabrication-locale', 'carte-bancaire', 'especes', 'epv'],
    hours: [...weekdays(0, 5, '09:00', '12:00'), ...weekdays(0, 5, '14:00', '18:00')],
    status: 'VALIDATED',
    plan: 'PREMIUM',
    owner: { first: 'Arnaud', last: 'Guyon', email: 'arnaud@distillerie-du-val.fr' },
    siret: '32165498700016',
    legalName: 'DISTILLERIE DU VAL SA',
    products: [
      ['Absinthe « La Bleue de la Loue »', '38 €', I.toast],
      ['Kirsch de Mouthier', '32 €', I.vine],
      ['Visite & dégustation', '12 € · dès 18 ans', I.workshop],
    ],
    updatedDaysAgo: 2,
  },
  {
    key: 'b15',
    name: 'Le Bistrot Courbet',
    category: 'bistrot',
    activity: 'Bistrot',
    commune: 'Ornans',
    lat: 47.1063,
    lng: 6.1455,
    street: '1 place Gustave Courbet',
    phone: '0381571264',
    email: 'bistrot.courbet@exemple.test',
    cover: I.food,
    tagline: 'Bistrot de pays face au musée Courbet',
    description:
      "Face au musée Courbet, un bistrot de pays où l'on vient pour le café du matin comme pour le dîner du soir : croûte aux morilles, saucisse de Morteau, planches à partager et vins au verre. Terrasse sur la place aux beaux jours, concerts le premier vendredi du mois.",
    attrs: ['terrasse', 'carte-bancaire', 'especes', 'tickets-resto', 'produits-locaux'],
    hours: [...weekdays(1, 6, '11:30', '23:00')],
    status: 'VALIDATED',
    plan: 'ESSENTIEL',
    owner: { first: 'Yann', last: 'Brocard', email: 'yann@bistrot-courbet.fr' },
    siret: '48912365400012',
    legalName: 'SAS BISTROT COURBET',
    products: [
      ['Croûte aux morilles', '19 €', I.food],
      ['Planche comtoise à partager', '16 €', I.board],
    ],
    updatedDaysAgo: 4,
  },
  {
    key: 'b16',
    name: 'Ébénisterie Rolland',
    category: 'ebeniste',
    activity: 'Ébéniste',
    commune: 'Amancey',
    lat: 47.0421,
    lng: 6.0762,
    street: '15 Grande rue',
    phone: '0381864390',
    cover: I.vases,
    tagline: 'Mobilier sur mesure et restauration',
    description: 'Mobilier sur mesure, marqueterie et restauration de meubles anciens.',
    attrs: ['fabrication-locale', 'sur-devis'],
    hours: [...weekdays(0, 4, '08:00', '12:00'), ...weekdays(0, 4, '14:00', '17:30')],
    status: 'PRECREATED',
    plan: 'ESSENTIEL',
    siret: '75312468900014',
    legalName: 'ROLLAND PAUL',
    updatedDaysAgo: 200,
  },
];

// ─── Offres d'emploi (P8) ───────────────────────────────────────────────────
export type JobSeed = {
  est: string;
  title: string;
  contract: 'CDI' | 'CDD' | 'ALTERNANCE' | 'SAISONNIER' | 'STAGE';
  start: string;
  salary: string;
  time: string;
  desc: string;
  missions: string[];
  profile: string[];
  daysAgo: number;
};

export const JOBS: JobSeed[] = [
  {
    est: 'b1',
    title: 'Apprenti·e boulanger·e',
    contract: 'ALTERNANCE',
    start: 'Septembre 2027',
    salary: 'Grille apprentissage + prime',
    time: 'Temps plein · début 4h',
    desc: "Vous rejoignez une boulangerie familiale de 6 personnes, reconnue pour son levain naturel et ses galettes comtoises. Formation en alternance avec le CFA de Besançon.",
    missions: ['Préparer les pâtes et entretenir le levain', 'Façonner et cuire pains et viennoiseries', 'Participer à la vente en boutique le samedi'],
    profile: ['Entrée en CAP boulanger', 'Goût du travail manuel et du produit', 'Ponctualité : les journées commencent tôt'],
    daysAgo: 3,
  },
  {
    est: 'b3',
    title: 'Serveur·se saison été',
    contract: 'SAISONNIER',
    start: 'Juin 2027 · 4 mois',
    salary: '1 850 € brut + pourboires',
    time: 'Temps plein · logement possible',
    desc: "Au bord de la Loue, le Relais accueille jusqu'à 80 couverts en terrasse l'été. Équipe soudée, cuisine de produits locaux.",
    missions: ['Accueillir et conseiller la clientèle', 'Assurer le service en salle et en terrasse', 'Participer à la mise en place et au rangement'],
    profile: ['Première expérience en restauration appréciée', 'Sourire et sens du collectif', 'Disponible les week-ends'],
    daysAgo: 5,
  },
  {
    est: 'b5',
    title: 'Plombier chauffagiste',
    contract: 'CDI',
    start: 'Dès que possible',
    salary: '2 300 – 2 700 € brut',
    time: 'Temps plein · véhicule fourni',
    desc: 'Entreprise certifiée RGE de 4 salariés, spécialisée dans les pompes à chaleur et le dépannage de chaudières sur tout le Val de Loue.',
    missions: ['Installer et mettre en service des équipements', "Réaliser les dépannages et l'entretien", "Conseiller les clients sur les économies d'énergie"],
    profile: ['CAP/BP plombier chauffagiste', 'Permis B indispensable', 'Autonomie et rigueur'],
    daysAgo: 6,
  },
  {
    est: 'b4',
    title: 'Menuisier·e poseur·se',
    contract: 'CDI',
    start: 'Janvier 2027',
    salary: '2 100 – 2 500 € brut',
    time: 'Temps plein · 35 h',
    desc: 'Atelier de menuiserie traditionnelle travaillant le bois des forêts du Doubs : escaliers, agencements et fenêtres sur mesure.',
    missions: ['Fabriquer en atelier à partir de plans', 'Poser chez les particuliers', 'Participer aux relevés de cotes'],
    profile: ['CAP menuisier ou expérience équivalente', 'Maîtrise des machines-outils', 'Soin du détail'],
    daysAgo: 9,
  },
  {
    est: 'b6',
    title: 'Vendeur·se conseil',
    contract: 'CDD',
    start: 'Novembre · 3 mois',
    salary: '1 900 € brut',
    time: '28 h / semaine',
    desc: 'La Cave Comtoise renforce son équipe pour les fêtes : vins du Jura, spiritueux et coffrets cadeaux.',
    missions: ['Conseiller les clients en boutique', 'Préparer les commandes click & collect', 'Animer les dégustations du samedi'],
    profile: ['Intérêt pour le vin et les produits locaux', 'Aisance relationnelle', "Disponible en fin d'année"],
    daysAgo: 2,
  },
  {
    est: 'b14',
    title: 'Stage marketing',
    contract: 'STAGE',
    start: 'Avril 2027 · 6 mois',
    salary: 'Gratification légale',
    time: 'Temps plein',
    desc: "Distillerie familiale depuis 1920, en plein développement à l'export. Vous travaillez directement avec la direction.",
    missions: ['Animer les réseaux sociaux', 'Organiser les visites et événements', 'Préparer les salons professionnels'],
    profile: ['Bac+3 à Bac+5 marketing / communication', 'Anglais courant', "Créativité et esprit d'initiative"],
    daysAgo: 12,
  },
  {
    est: 'b10',
    title: 'Cuisinier·e',
    contract: 'CDI',
    start: 'Février 2027',
    salary: '2 200 € brut + repas',
    time: 'Temps plein · coupure',
    desc: 'Auberge de 40 couverts à Mouthier-Haute-Pierre, cuisine de terroir revisitée, produits à moins de 30 km.',
    missions: ['Préparer les entrées et plats du jour', 'Travailler les produits des fermes voisines', "Participer à l'élaboration de la carte"],
    profile: ["CAP cuisine et 2 ans d'expérience", 'Passion pour les produits locaux', "Esprit d'équipe"],
    daysAgo: 15,
  },
  {
    est: 'b7',
    title: 'Aide maraîcher·e',
    contract: 'SAISONNIER',
    start: 'Mars 2027 · 6 mois',
    salary: 'SMIC',
    time: '35 h · en plein air',
    desc: 'Ferme maraîchère bio de 3 hectares, vente directe et paniers hebdomadaires pour 120 familles.',
    missions: ['Semer, planter, désherber', 'Récolter et préparer les paniers', 'Tenir le stand du marché du samedi'],
    profile: ['Aucun diplôme exigé', 'Goût du travail en extérieur', 'Motivation et endurance'],
    daysAgo: 20,
  },
];

// ─── Circuits (P6 / C6) ─────────────────────────────────────────────────────
export const CIRCUITS = [
  {
    slug: 'fil-de-la-loue',
    name: 'Le fil de la Loue gourmande',
    stops: ['b9', 'b1', 'b15', 'b3', 'b11', 'b14', 'b10'],
    km: '24',
    dur: '1 journée',
    mode: 'Voiture ou vélo électrique',
    img: I.forest,
    tagColor: '#F4B266',
    meta: 'Chocolat, pain, truite, miel, absinthe',
    reward: '5 tampons = un panier garni offert',
    threshold: 5,
    description:
      "De la chocolaterie d'Ornans aux alambics de Mouthier, sept étapes gourmandes le long de la rivière. Faites tamponner votre passeport à chaque arrêt en scannant le QR code en vitrine.",
  },
  {
    slug: 'mains-d-or',
    name: "Les mains d'or : métiers d'art",
    stops: ['b16', 'b8', 'b4'],
    km: '38',
    dur: '½ journée',
    mode: 'Voiture',
    img: I.pottery,
    tagColor: '#DCD3F3',
    meta: 'Céramique, ébénisterie, menuiserie',
    reward: '3 tampons = un atelier découverte',
    threshold: 3,
    description: "Céramistes, ébénistes et menuisiers vous ouvrent leurs ateliers : le geste, l'outil, la matière.",
  },
  {
    slug: 'producteurs-en-direct',
    name: 'Producteurs en direct',
    stops: ['b7', 'b13', 'b2', 'b11'],
    km: '42',
    dur: '1 journée',
    mode: 'Voiture',
    img: I.carrots,
    tagColor: '#D6E8B4',
    meta: 'Légumes bio, vrac, Comté, miel',
    reward: '4 tampons = un bon de 10 €',
    threshold: 4,
    description: 'Des champs au comptoir : légumes bio, Comté du plateau, miel des côtes et épicerie vrac.',
  },
];

export const OFFERS: Record<string, string> = {
  b1: '-10 % galettes',
  b9: 'Coffret -15 %',
  b8: 'Atelier gratuit',
  b2: 'Dégustation offerte',
  b6: '-20 % 2e bouteille',
  b14: 'Emballage cadeau',
};

export const ADVENT = [
  'Vin chaud offert · Cave Comtoise',
  '-10 % galettes · Boulangerie Martin',
  'Atelier céramique · Lison',
  'Dégustation Comté · Plateau',
  'Coffret -15 % · Vuillemin',
  'Visite distillerie',
  'Menu enfant offert · Bistrot',
  'Emballage cadeau gratuit',
  'Miel de sapin -20 %',
  'Tombola des commerçants',
  'Concert place Courbet',
  'Marché de nuit Quingey',
  'Chocolat chaud offert · Vuillemin',
  'Atelier couronne de l’Avent',
  'Livraison offerte · Vrac & Co',
  'Balade contée à Mouthier',
  '-15 % sur les planches · Bistrot',
  'Dégustation de vins du Jura',
  'Calendrier photo des commerçants',
  'Démonstration de tournage · Lison',
  'Marché de Noël d’Ornans',
  'Bûche à gagner · Boulangerie Martin',
  'Visite du Père Noël en barque',
  'Grande tombola de Noël',
];

export const ADVENT_EST: Record<number, string> = { 1: 'b6', 2: 'b1', 3: 'b8', 4: 'b2', 5: 'b9', 6: 'b14', 7: 'b15', 9: 'b11', 13: 'b9', 15: 'b13', 17: 'b15', 20: 'b8', 22: 'b1' };
