<?php
/**
 * Actions de l'association (rubrique « Nos actions ») : une page par action. Modifiables dans
 * le back-office (Site de l'association › Actions). Les liens « musee: » mènent au musée en
 * ligne (adresse réglée dans Réglages › Général).
 */

return [
    [
        'slug' => 'musee-en-ligne',
        'menu' => 'Le musée en ligne',
        'title' => 'Le musée en ligne du FCSM',
        'icon' => '◆',
        'image' => '2024/04/img116-fv.jpg',
        'excerpt' => 'Notre grand projet : près d’un siècle d’histoire sochalienne, gratuitement accessible à tous.',
        'lead' => 'Matchs, joueurs, entraîneurs, dirigeants, supporters, stades et symboles : l’histoire du FC Sochaux-Montbéliard rassemblée en un seul lieu, ouvert à tous et gratuit.',
        'body' => '<h2>Un musée qui ne ferme jamais</h2><p>Chaque match a sa fiche : composition, buteurs, récit, photos et vidéos quand elles existent. Chaque joueur a la sienne, avec son parcours sous le maillot jaune et bleu. Les saisons, les adversaires, les records et les grands chiffres du club sont calculés à partir de cette base, vérifiée par nos historiens bénévoles.</p><h2>Jouer avec l’histoire</h2><p>Le musée se visite aussi en s’amusant : quiz des supporters, album de cartes à collectionner, comparateur de maillots, frise chronologique, carte des stades et des épopées, Fil jaune pour relier deux joueurs par leurs matchs joués ensemble… et le Rétro-Direct, qui rejoue les grands matchs minute par minute, le jour anniversaire.</p><h2>Un musée participatif</h2><p>Une photo, un programme, une erreur à corriger, un souvenir de match ? Chacun peut contribuer depuis n’importe quelle fiche. Chaque proposition est relue par l’équipe avant d’être publiée.</p>',
        'stats' => true,
        'cta_label' => 'Entrer dans le musée',
        'cta_url' => 'musee:/',
        'cta2_label' => 'Contribuer au musée',
        'cta2_url' => 'musee:/contribuer/',
    ],
    [
        'slug' => 'videos-et-reseaux',
        'menu' => 'Vidéos et réseaux sociaux',
        'title' => 'Vidéos et réseaux sociaux',
        'icon' => '▶',
        'image' => '2024/03/1.TNS_.jpeg',
        'excerpt' => 'Plus de 1 400 vidéos sur YouTube et une communauté de plus de 11 000 passionnés.',
        'lead' => 'C’est là que tout a commencé : une communauté qui partage chaque jour photos, vidéos et souvenirs du FCSM.',
        'body' => '<h2>Notre chaîne YouTube</h2><p>Résumés de matchs d’hier et d’avant-hier, buts mythiques, reportages et documents rares : plus de 1 400 vidéos à regarder et à partager. Beaucoup sont aussi intégrées aux fiches du musée en ligne, au bon endroit, à côté du match qu’elles racontent.</p><h2>Une communauté vivante</h2><p>Sur Facebook, Instagram et X, plus de 11 000 passionnés échangent chaque jour. On y identifie des joueurs sur des photos anciennes, on y retrouve des billets de match, on s’y raconte des souvenirs de tribune. C’est souvent là que naissent les plus belles trouvailles du musée.</p>',
        'videos' => true,
        'cta_label' => 'Voir la chaîne YouTube',
        'cta_url' => 'social:youtube',
        'cta2_label' => 'Rejoindre la communauté',
        'cta2_url' => 'social:facebook',
    ],
    [
        'slug' => 'collections-et-archives',
        'menu' => 'Collections et archives',
        'title' => 'Collecter et préserver les archives',
        'icon' => '▤',
        'image' => '2024/09/IMG_20221102_151654_edit_352581944522239-scaled.jpg',
        'excerpt' => 'Affiches, programmes, billets, photos, coupures de presse : sauver ce qui raconte le club.',
        'lead' => 'Dans les greniers et les albums de famille dorment des trésors : affiches, programmes, billets, photos, fanions, coupures de presse. Notre mission : les sauver avant qu’ils ne disparaissent.',
        'body' => '<h2>Collecter</h2><p>Supporters, anciens joueurs et leurs familles nous confient leurs documents, en prêt pour numérisation ou en don. Un simple scan ou une photo de bonne qualité suffit souvent : l’original reste chez vous.</p><h2>Numériser et documenter</h2><p>Chaque pièce est numérisée en haute définition, restaurée si besoin, puis datée, légendée et reliée aux matchs et aux joueurs qu’elle concerne. Les droits et la source sont toujours indiqués.</p><h2>Montrer</h2><p>Les pièces rejoignent les réserves du musée en ligne : maillots, affiches, programmes, photos, presse et objets de supporters, consultables par tous.</p>',
        'cta_label' => 'Confier une archive',
        'cta_url' => 'musee:/contribuer/',
        'cta2_label' => 'Voir les réserves du musée',
        'cta2_url' => 'musee:/reserves/',
    ],
    [
        'slug' => 'expositions-et-rencontres',
        'menu' => 'Expositions et rencontres',
        'title' => 'Expositions et rencontres',
        'icon' => '◎',
        'image' => '2024/02/1.-bonal.jpeg',
        'excerpt' => 'Faire sortir l’histoire des écrans : expositions, rencontres, projections.',
        'lead' => 'L’histoire du club se partage aussi en vrai : autour d’une exposition, d’une projection ou d’une rencontre avec ceux qui l’ont écrite.',
        'body' => '<h2>Des rendez-vous à construire ensemble</h2><p>L’association souhaite multiplier les occasions de se retrouver : expositions de pièces d’archives, rencontres avec d’anciens joueurs, soirées de projection de matchs mythiques, présence lors des grands rendez-vous du club et des fêtes locales.</p><h2>Vous avez un lieu, une idée, une date ?</h2><p>Mairie, médiathèque, club de supporters, entreprise, association de quartier : contactez-nous pour imaginer ensemble un événement autour de l’histoire du FCSM. Les prochains rendez-vous sont annoncés dans l’agenda.</p>',
        'cta_label' => 'Voir l’agenda',
        'cta_url' => '/agenda/',
        'cta2_label' => 'Proposer un événement',
        'cta2_url' => '/contact/?objet=evenement',
        'a_verifier' => true,
        'a_verifier_note' => 'Décrire les expositions et rencontres réellement organisées (ou prévues) par l’association.',
    ],
    [
        'slug' => 'apres-midi-bonal',
        'menu' => 'Raconte-moi Bonal',
        'title' => 'Raconte-moi Bonal',
        'icon' => '❝',
        'image' => '2024/12/claude-quittet-lors-de-la-finale-de-1967-perdue-par-sochaux-face-a-lyon-il-est-felicite-par-le-general-de-gaulle-photo-d-archives-er-1480960505.jpg',
        'excerpt' => 'Un kit souvenirs mensuel à imprimer, pour faire revivre les grands matchs auprès des anciens.',
        'lead' => 'Pour ceux qui ont vu jouer Sochaux il y a cinquante ans, un match raconté, c’est une madeleine. Raconte-moi Bonal fait revivre ces souvenirs dans les maisons de retraite, les clubs et les familles.',
        'body' => '<h2>Un kit à imprimer, chaque mois</h2><p>Chaque mois, le musée en ligne propose un kit souvenirs gratuit de quatre pages, en gros caractères : le grand match d’il y a 30 ou 40 ans, des visages à reconnaître, un quiz des anciens et des questions pour raconter. Animateurs, soignants, bénévoles ou petits-enfants : il suffit de l’imprimer et de le partager.</p><h2>« Ils y étaient »</h2><p>Les souvenirs recueillis pendant ces après-midi sont précieux. Un QR code du kit mène au formulaire de témoignage : une fois relus par l’équipe, les récits rejoignent la fiche du match, dans « Ils y étaient ». Une façon de transmettre ces mémoires aux générations suivantes.</p>',
        'cta_label' => 'Télécharger le kit du mois',
        'cta_url' => 'musee:/interactif/souvenirs/',
        'cta2_label' => 'Organiser une séance',
        'cta2_url' => '/contact/?objet=apres-midi-bonal',
    ],
    [
        'slug' => 'centenaire-2028',
        'menu' => 'Centenaire 2028',
        'title' => 'Objectif centenaire',
        'icon' => '100',
        'image' => '2025/03/que-le-jaune-soit-or-et-que-le-bleu-soit-roi-1652281058.jpg',
        'excerpt' => 'Le FC Sochaux-Montbéliard aura 100 ans : nous préparons ce rendez-vous avec vous.',
        'lead' => 'Cent ans de jaune et de bleu, ça se prépare. L’association mobilise sa communauté pour arriver au centenaire avec une mémoire du club complète, vérifiée et partagée.',
        'body' => '<h2>100 moments d’histoire</h2><p>Chaque semaine jusqu’au centenaire, le musée en ligne révèle un moment marquant de l’histoire du club : un match, un geste, une saison, un personnage. Cent moments pour cent ans.</p><h2>Le Onze de légende</h2><p>Gardien, défenseurs, milieux, attaquants : le public compose son équipe idéale de tous les temps. Le Onze de légende du centenaire sera dévoilé le jour anniversaire.</p><h2>Sauver 100 ans d’archives</h2><p>Notre objectif : que chaque saison, chaque match et chaque joueur ait sa trace au musée d’ici le centenaire. Pour y arriver, nous avons besoin de vos archives, de votre temps et de votre soutien.</p>',
        'countdown' => true,
        'cta_label' => 'Voter pour le Onze de légende',
        'cta_url' => 'musee:/centenaire/#onze',
        'cta2_label' => 'Découvrir les 100 moments',
        'cta2_url' => 'musee:/centenaire/100-moments/',
    ],
];
