<?php
/**
 * Schéma des réglages modifiables dans le back-office (Réglages).
 *
 * Types : text, wysiwyg (éditeur visuel : tous les textes longs), email, url, number, bool, select,
 * secret, date, datetime, color, image.
 * Un champ « secret » est chiffré au repos et n'est jamais réaffiché en clair.
 * « options_from » indique une liste remplie dynamiquement (ex. modèles Gemini).
 */

return [
    'general' => [
        'label' => 'Général',
        'fields' => [
            'site_name' => ['label' => 'Nom du site', 'type' => 'text', 'default' => 'Sochaux Rétro'],
            'site_tagline' => ['label' => 'Signature', 'type' => 'text', 'default' => 'Le musée en ligne du FCSM'],
            'base_url' => ['label' => 'Adresse du site', 'type' => 'url', 'default' => 'https://musee.fcsochauxretro.com', 'help' => 'Sans barre oblique finale.'],
            'contact_email' => ['label' => 'E-mail de réception des messages', 'type' => 'email', 'default' => ''],
            'domain_label' => ['label' => 'Adresse affichée sur les images de partage', 'type' => 'text', 'default' => 'musee.fcsochauxretro.com'],
            'front_password' => ['label' => 'Mot de passe d’accès au site public (pré-lancement)', 'type' => 'secret', 'default' => '', 'help' => 'Laisser vide pour un site ouvert à tous.'],
            'noindex' => ['label' => 'Masquer le site aux moteurs de recherche', 'type' => 'bool', 'default' => false, 'help' => 'Même ouvert au public, le site n’est pas indexé (Google…). Inutile tant que la page d’attente est active : rien n’est indexé.'],
            'debug' => ['label' => 'Afficher les erreurs (développement)', 'type' => 'bool', 'default' => false],
        ],
    ],
    'waiting' => [
        'label' => "Page d'attente",
        'fields' => [
            'enabled' => ['label' => "Activer la page d'attente", 'type' => 'bool', 'default' => true, 'help' => "Les visiteurs voient uniquement cette page et rien n'est indexé par les moteurs de recherche. Les membres connectés du back-office voient le site normalement. Active dès l'installation : décochez le jour de l'ouverture."],
            'logo' => ['label' => 'Logo', 'type' => 'image', 'default' => '', 'help' => 'Vide : logo Sochaux Rétro.'],
            'title' => ['label' => 'Titre', 'type' => 'text', 'default' => 'Le musée ouvre bientôt ses portes'],
            'text' => ['label' => 'Texte', 'type' => 'wysiwyg', 'default' => "<p>Sochaux Rétro prépare son nouveau musée en ligne : près d'un siècle de jaune et de bleu, rassemblé pièce par pièce.</p><p>Revenez très vite !</p>"],
            'countdown' => ['label' => 'Afficher un compte à rebours', 'type' => 'bool', 'default' => false],
            'countdown_date' => ['label' => 'Date et heure cibles du compte à rebours', 'type' => 'datetime', 'default' => '2026-12-01T10:00', 'show_if' => 'countdown'],
            'countdown_label' => ['label' => 'Intitulé du compte à rebours', 'type' => 'text', 'default' => "Ouverture dans", 'show_if' => 'countdown'],
            'show_social' => ['label' => 'Afficher les liens vers les réseaux sociaux', 'type' => 'bool', 'default' => true],
            'teaser' => ['label' => 'Afficher le teaser vidéo (1 min 55)', 'type' => 'bool', 'default' => false, 'help' => 'Décoché : la vidéo reste secrète, introuvable par le public. « Aperçu avec le teaser » la montre à l’équipe sans l’activer.'],
        ],
    ],
    'home' => [
        'label' => 'Accueil',
        'fields' => [
            'intro_title' => ['label' => 'Titre de la page d’accueil (onglet du navigateur, Google)', 'type' => 'text', 'default' => 'Musée numérique FCSM - Sochaux Rétro'],
            'intro_text' => ['label' => 'Présentation du musée (description pour Google et le partage)', 'type' => 'wysiwyg', 'default' => "Sochaux Rétro : l'histoire de notre club s'écrit maintenant ! Bienvenue au musée numérique de notre club, le Football Club Sochaux Montbéliard - FCSM.\nUn projet de Sochaux Rétro !"],
            'slider_count' => ['label' => 'Nombre de slides tirées au hasard dans « À la une »', 'type' => 'number', 'default' => 5],
            'counter_community' => ['label' => 'Compteur : membres de la communauté', 'type' => 'text', 'default' => '11000+'],
            'counter_videos' => ['label' => 'Compteur : vidéos YouTube', 'type' => 'text', 'default' => '1400+'],
            'centenary_date' => ['label' => 'Date du centenaire (compte à rebours)', 'type' => 'date', 'default' => '2028-05-20'],
            'daily_figure' => ['label' => 'Afficher « Le chiffre du jour » (un des 100 chiffres du FCSM, un nouveau chaque jour)', 'type' => 'bool', 'default' => true],
            'teaser' => ['label' => 'Afficher le teaser vidéo sur l’accueil (le public le voit à l’ouverture du site)', 'type' => 'bool', 'default' => true],
        ],
    ],
    'social' => [
        'label' => 'Réseaux sociaux',
        'fields' => [
            'facebook' => ['label' => 'Facebook', 'type' => 'url', 'default' => 'https://www.facebook.com/groups/fcsmvintage'],
            'instagram' => ['label' => 'Instagram', 'type' => 'url', 'default' => 'https://instagram.com/sochauxretro'],
            'x' => ['label' => 'X (Twitter)', 'type' => 'url', 'default' => 'https://x.com/SochauxRetro'],
            'youtube' => ['label' => 'YouTube', 'type' => 'url', 'default' => 'https://youtube.com/@SochauxRetro'],
            'official' => ['label' => 'Site officiel du FC Sochaux-Montbéliard (lien discret sous le titre de l’en-tête)', 'type' => 'url', 'default' => 'https://www.fcsochaux.fr', 'help' => 'Vide : lien masqué.'],
        ],
    ],
    'footer' => [
        'label' => 'Pied de page',
        'fields' => [
            'title' => ['label' => 'Titre, 1re ligne', 'type' => 'text', 'default' => 'Un partenariat ?'],
            'title_en' => ['label' => 'Titre, 1re ligne (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'title2' => ['label' => 'Titre, 2e ligne', 'type' => 'text', 'default' => 'Besoin d\'une information ?'],
            'title2_en' => ['label' => 'Titre, 2e ligne (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'text' => ['label' => 'Phrase sous le titre', 'type' => 'text', 'default' => 'On vous répond dans les plus brefs délais.'],
            'text_en' => ['label' => 'Phrase sous le titre (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'button1' => ['label' => 'Bouton jaune : texte', 'type' => 'text', 'default' => 'Contactez-nous', 'help' => 'Vide : bouton masqué.'],
            'button1_en' => ['label' => 'Bouton jaune : texte (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'button1_link' => ['label' => 'Bouton jaune : lien', 'type' => 'text', 'default' => '/contact/', 'help' => 'Page du musée (/contact/) ou autre site (https://…).'],
            'button2' => ['label' => 'Bouton contour : texte', 'type' => 'text', 'default' => 'L\'équipe Sochaux rétro', 'help' => 'Vide : bouton masqué.'],
            'button2_en' => ['label' => 'Bouton contour : texte (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'button2_link' => ['label' => 'Bouton contour : lien', 'type' => 'text', 'default' => '/supporters/l-equipe-de-sochaux-retro/', 'help' => 'Page du musée (/contact/) ou autre site (https://…).'],
            'tagline' => ['label' => 'Accroche sous le logo', 'type' => 'text', 'default' => 'Le musée en ligne du FCSM'],
            'tagline_en' => ['label' => 'Accroche sous le logo (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'copyright' => ['label' => 'Ligne du bas', 'type' => 'text', 'default' => '© {année} FC Sochaux rétro', 'help' => '{année} : l’année en cours.'],
            'copyright_en' => ['label' => 'Ligne du bas (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'credit' => ['label' => 'Mention « Propulsé par »', 'type' => 'text', 'default' => 'Propulsé par', 'help' => 'Vide : mention masquée.'],
            'credit_en' => ['label' => 'Mention « Propulsé par » (anglais)', 'type' => 'text', 'default' => '', 'help' => 'Vide : la traduction d’origine, tant que le texte français n’a pas changé.'],
            'credit_name' => ['label' => 'Nom affiché après la mention', 'type' => 'text', 'default' => 'LE-DIGITAL.com'],
            'credit_link' => ['label' => 'Lien de ce nom', 'type' => 'text', 'default' => 'https://www.le-digital.com'],
        ],
    ],
    'ai' => [
        'label' => 'Assistant IA',
        'fields' => [
            'enabled' => ['label' => 'Activer l’assistant (bulle en bas à droite)', 'type' => 'bool', 'default' => false],
            'gemini_api_key' => ['label' => 'Clé API Gemini', 'type' => 'secret', 'default' => '', 'help' => 'Clé Google AI Studio. Elle reste sur le serveur et n’est jamais envoyée au navigateur.'],
            'model' => ['label' => 'Modèle de réponse', 'type' => 'select', 'options_from' => 'gemini_generate_models', 'default' => ''],
            'embedding_model' => ['label' => 'Modèle d’embedding (recherche dans les données)', 'type' => 'select', 'options_from' => 'gemini_embedding_models', 'default' => ''],
            'assistant_name' => ['label' => 'Nom de l’assistant', 'type' => 'text', 'default' => 'Le guide du musée'],
            'welcome' => ['label' => 'Message d’accueil', 'type' => 'wysiwyg', 'default' => 'Bonjour ! Je connais tous les matchs, joueurs et personnages du musée Sochaux Rétro. Posez-moi votre question.'],
            'system_prompt' => ['label' => 'Consignes de l’assistant', 'type' => 'wysiwyg', 'default' => "Tu es le guide du musée numérique Sochaux Rétro, consacré à l'histoire du FC Sochaux-Montbéliard (FCSM).\nRéponds uniquement à partir des extraits du musée fournis. Si l'information n'y figure pas, dis-le simplement et propose une recherche proche.\nCite les fiches utilisées. Réponds dans la langue de la question, avec un ton chaleureux et précis."],
            'temperature' => ['label' => 'Créativité (0 = factuel, 1 = libre)', 'type' => 'number', 'default' => 0.3, 'step' => 0.1, 'min' => 0, 'max' => 1],
            'max_output_tokens' => ['label' => 'Longueur maximale des réponses (jetons)', 'type' => 'number', 'default' => 800],
            'context_chunks' => ['label' => 'Nombre d’extraits envoyés à Gemini par question', 'type' => 'number', 'default' => 8],
            'daily_limit' => ['label' => 'Questions par visiteur et par jour', 'type' => 'number', 'default' => 20],
            'global_daily_limit' => ['label' => 'Questions par jour pour tout le site (plafond de coût)', 'type' => 'number', 'default' => 2000],
            'log_questions' => ['label' => 'Conserver les questions posées (consultables dans le back-office)', 'type' => 'bool', 'default' => true],
            'log_retention_days' => ['label' => 'Durée de conservation des questions (jours)', 'type' => 'number', 'default' => 365],
        ],
    ],
    'translation' => [
        'label' => 'Traduction',
        'fields' => [
            'languages' => ['label' => 'Langues proposées (codes séparés par des virgules)', 'type' => 'text', 'default' => 'fr,en'],
            'auto_translate' => ['label' => 'Traduire automatiquement les contenus avec Gemini', 'type' => 'bool', 'default' => true, 'help' => 'Les traductions sont stockées et corrigeables ; le français reste la référence.'],
        ],
    ],
    'correcteur' => [
        'label' => 'Correcteur',
        'fields' => [
            'background' => ['label' => 'Vérifier l’orthographe de toutes les fiches en tâche de fond', 'type' => 'bool', 'default' => true, 'help' => 'Les corrections proposées s’affichent dans Qualité › Orthographe et dans chaque fiche. Rien n’est modifié sans l’accord d’un historien. Sans clé Gemini, seules les règles de base sont appliquées.'],
            'daily_calls' => ['label' => 'Appels à Gemini par jour pour la tâche de fond (plafond de coût)', 'type' => 'number', 'default' => 300, 'help' => 'Un appel vérifie environ 6 000 caractères. Un texte déjà vérifié n’est jamais renvoyé à Gemini. La vérification depuis l’éditeur n’est pas plafonnée.'],
            'typography' => ['label' => 'Proposer aussi les corrections typographiques (« À », « 1re », « 2e », espaces)', 'type' => 'bool', 'default' => true, 'help' => 'Décoché, seules les fautes de langue et de ponctuation sont signalées : « 2ème », « A l’extérieur » ou « l’ équipe » ne sont plus proposés.'],
        ],
    ],
    'recherche' => [
        'label' => 'Recherche sur le web',
        'fields' => [
            'enabled' => ['label' => 'Bouton « Chercher sur le web » dans les fiches (aide à l’historien)', 'type' => 'bool', 'default' => true, 'help' => 'Gemini cherche avec Google ce qui pourrait corriger ou compléter la fiche et propose, avec ses sources. Rien n’est modifié : l’historien vérifie et reporte lui-même. Seulement quand on clique : jamais en tâche de fond.'],
            'model' => ['label' => 'Modèle qui fait la recherche', 'type' => 'select', 'options_from' => 'gemini_generate_models', 'empty' => 'Le « Modèle de réponse » de l’assistant', 'default' => '', 'help' => 'Un modèle Flash (sans « Lite ») cherche et compare mieux. Avec Gemini 3, 5 000 recherches Google gratuites par mois, puis 1,4 centime de dollar l’une (une recherche de fiche en lance 2 à 5).'],
            'monthly_limit' => ['label' => 'Recherches par mois pour tout le back-office (plafond de coût, 0 = sans limite)', 'type' => 'number', 'default' => 300, 'min' => 0],
        ],
    ],
    'audio' => [
        'label' => 'Fiches audio',
        'fields' => [
            'enabled' => ['label' => 'Bouton « Écouter » sur les fiches (explication audio de la fiche)', 'type' => 'bool', 'default' => true, 'help' => 'Sans voix IA, le texte est lu par la voix du navigateur du visiteur : gratuit.'],
            'max_minutes' => ['label' => 'Durée maximale d’une explication (minutes)', 'type' => 'number', 'default' => 3, 'step' => 0.5, 'min' => 0.5, 'max' => 10, 'help' => 'Chaque fiche est expliquée en entier, aussi longuement que son contenu le demande, sans dépasser cette durée (environ 150 mots par minute) : une fiche courte reste courte. Plus long : voix IA plus chère. Changer la durée fait refaire les textes rédigés par l’IA.'],
            'ai_text' => ['label' => 'Faire rédiger les explications par l’IA lors du traitement groupé (sinon : texte automatique tiré de la fiche)', 'type' => 'bool', 'default' => true, 'help' => 'Environ 0,05 centime par fiche avec un modèle Flash-Lite (« Modèle de réponse » de l’assistant), moitié prix en traitement groupé. Chaque texte reste modifiable dans la fiche.'],
            'text_model' => ['label' => 'Modèle qui rédige les textes audio', 'type' => 'select', 'options_from' => 'gemini_generate_models', 'empty' => 'Le « Modèle de réponse » de l’assistant', 'default' => '', 'help' => 'Un modèle Flash (sans « Lite ») raconte mieux : quelques euros pour tout le musée en traitement groupé, contre environ 1 € avec Flash-Lite.'],
            'tts_model' => ['label' => 'Modèle de voix IA', 'type' => 'select', 'options_from' => 'gemini_tts_models', 'default' => ''],
            'voice' => ['label' => 'Voix', 'type' => 'select', 'default' => 'Charon', 'options' => [
                'Charon' => 'Charon (informative)', 'Sadaltager' => 'Sadaltager (savante)', 'Gacrux' => 'Gacrux (mûre)', 'Sulafat' => 'Sulafat (chaleureuse)',
                'Achird' => 'Achird (amicale)', 'Iapetus' => 'Iapetus (claire)', 'Schedar' => 'Schedar (égale)', 'Kore' => 'Kore (ferme)', 'Orus' => 'Orus (ferme)',
                'Algenib' => 'Algenib (rocailleuse)', 'Vindemiatrix' => 'Vindemiatrix (douce)', 'Puck' => 'Puck (enjouée)',
            ]],
            'auto_update' => ['label' => 'Refaire chaque nuit la voix IA des fiches modifiées (traitement groupé)', 'type' => 'bool', 'default' => true],
            'pages_ai' => ['label' => 'Faire raconter par l’IA les pages de synthèse (face-à-face, saisons, bilans, records, chiffres)', 'type' => 'bool', 'default' => true, 'help' => 'Après le premier lancement pour tout le musée (Système › Fiches audio, où l’on peut d’abord essayer sur une page), chaque nuit, les récits manquants ou dont les chiffres ont changé sont rédigés en traitement groupé, en français et en anglais (moins d’un euro pour tout le musée avec Flash-Lite). En attendant, le récit automatique, gratuit, est lu.'],
            'pages_voice' => ['label' => 'Voix IA pour les récits des pages de synthèse (enregistrée après chaque nouveau récit)', 'type' => 'bool', 'default' => true, 'help' => 'La voix naturelle de Gemini réglée ci-dessus, en français et en anglais : environ 15 à 20 € pour tout le musée en traitement groupé (le tarif des voix double au 1er janvier 2027), puis quelques centimes quand un récit est refait. Sinon : voix du navigateur, gratuite.'],
        ],
    ],
    'update' => [
        'label' => 'Mises à jour',
        'fields' => [
            'repo' => ['label' => 'Dépôt GitHub (propriétaire/nom)', 'type' => 'text', 'default' => 'ftholomier/poubelle'],
            'branch' => ['label' => 'Branche à suivre', 'type' => 'text', 'default' => 'claude/sweet-einstein-hawxrw', 'help' => 'La dernière version publiée sur cette branche est proposée dans Système › Mises à jour.'],
            'token' => ['label' => 'Jeton GitHub (facultatif)', 'type' => 'secret', 'default' => '', 'help' => 'Inutile pour un dépôt public. Nécessaire si le dépôt devient privé : GitHub › Settings › Developer settings › Fine-grained tokens, accès « Contents : Read-only » à ce seul dépôt.'],
        ],
    ],
    'couts' => [
        'label' => 'Coûts IA',
        'fields' => [
            'payer' => ['label' => 'Qui règle la facture Google (avance de frais)', 'type' => 'text', 'default' => '', 'help' => 'Nom imprimé sur le relevé mensuel que l’association rembourse (écran Système › Coûts IA).'],
            'eur_rate' => ['label' => 'Taux de change : 1 dollar = … euro', 'type' => 'number', 'default' => 0.86, 'step' => 0.0001, 'min' => 0.5, 'max' => 2, 'help' => 'Google fixe ses tarifs en dollars : reprenez le taux de votre facture pour que les euros correspondent.'],
            'monthly_budget' => ['label' => 'Budget mensuel en euros (0 = sans limite)', 'type' => 'number', 'default' => 0, 'step' => 0.01, 'min' => 0],
            'pause_tasks' => ['label' => 'Budget atteint : suspendre les tâches automatiques (traductions, correcteur, index de l’assistant)', 'type' => 'bool', 'default' => true, 'help' => 'Les règles de base du correcteur continuent, sans frais. Les boutons du back-office restent utilisables.'],
            'pause_assistant' => ['label' => 'Budget atteint : suspendre aussi l’assistant du site', 'type' => 'bool', 'default' => false, 'help' => 'Les visiteurs lisent alors « L’assistant fait une pause : revenez bientôt ! » jusqu’au 1er du mois suivant.'],
            'free_tier' => ['label' => 'Clé Gemini sur le niveau gratuit de Google (rien n’est facturé)', 'type' => 'bool', 'default' => false, 'help' => 'Les appels restent comptés, à 0 € ; le coût évité est indiqué à part.'],
        ],
    ],
    'donations' => [
        'label' => 'Dons',
        'fields' => [
            'enabled' => ['label' => 'Activer les dons', 'type' => 'bool', 'default' => false],
            'mode' => ['label' => 'Mode', 'type' => 'select', 'options' => ['test' => 'Test (aucun prélèvement réel)', 'live' => 'Production'], 'default' => 'test'],
            'currency' => ['label' => 'Devise', 'type' => 'select', 'options' => ['eur' => 'Euro (€)'], 'default' => 'eur'],
            'goal_amount' => ['label' => 'Objectif de la collecte (€)', 'type' => 'number', 'default' => 10000],
            'goal_label' => ['label' => 'Intitulé de la collecte', 'type' => 'text', 'default' => 'Objectif centenaire 2028'],
            'goal_start' => ['label' => 'Début de la collecte (pour la jauge)', 'type' => 'date', 'default' => '2026-01-01'],
            'min_amount' => ['label' => 'Montant libre minimum (€)', 'type' => 'number', 'default' => 2],
            'max_amount' => ['label' => 'Montant maximum en ligne (€)', 'type' => 'number', 'default' => 5000, 'help' => 'Au-delà, le donateur est invité à nous contacter (chèque, virement).'],
            'offset_amount' => ['label' => 'Dons reçus hors ligne à ajouter à la jauge (€)', 'type' => 'number', 'default' => 0],
            'offset_donors' => ['label' => 'Donateurs hors ligne à ajouter au compteur', 'type' => 'number', 'default' => 0],
            'notify' => ['label' => 'Prévenir l’équipe par e-mail à chaque don', 'type' => 'bool', 'default' => true],
            'stripe_public_key' => ['label' => 'Stripe : clé publique (pk_…)', 'type' => 'text', 'default' => ''],
            'stripe_secret_key' => ['label' => 'Stripe : clé secrète (sk_…)', 'type' => 'secret', 'default' => ''],
            'stripe_webhook_secret' => ['label' => 'Stripe : secret du webhook (whsec_…)', 'type' => 'secret', 'default' => '', 'help' => 'Adresse du webhook à déclarer chez Stripe : /api/dons/stripe/webhook'],
            'paypal_client_id' => ['label' => 'PayPal : Client ID', 'type' => 'text', 'default' => ''],
            'paypal_secret' => ['label' => 'PayPal : Secret', 'type' => 'secret', 'default' => ''],
            'paypal_webhook_id' => ['label' => 'PayPal : identifiant du webhook', 'type' => 'text', 'default' => '', 'help' => 'Adresse du webhook à déclarer chez PayPal : /api/dons/paypal/webhook'],
            'tax_receipts' => ['label' => 'Émettre des reçus fiscaux (association d’intérêt général)', 'type' => 'bool', 'default' => false],
            'org_name' => ['label' => 'Nom de l’association', 'type' => 'text', 'default' => 'Sochaux Rétro'],
            'org_address' => ['label' => 'Adresse de l’association', 'type' => 'wysiwyg', 'default' => ''],
            'org_rna' => ['label' => 'N° RNA ou SIREN', 'type' => 'text', 'default' => ''],
            'org_object' => ['label' => 'Objet de l’association (reçu fiscal)', 'type' => 'text', 'default' => 'Préservation et diffusion du patrimoine historique du FC Sochaux-Montbéliard'],
            'org_type' => ['label' => 'Qualité de l’organisme (reçu fiscal)', 'type' => 'select', 'options' => ['oig' => 'Œuvre ou organisme d’intérêt général', 'rup' => 'Association reconnue d’utilité publique', 'musee' => 'Musée de France'], 'default' => 'oig'],
            'org_signatory' => ['label' => 'Signataire des reçus (nom, qualité)', 'type' => 'text', 'default' => ''],
            'thanks_email' => ['label' => 'E-mail de remerciement', 'type' => 'wysiwyg', 'default' => "Merci {prenom} !\n\nVotre don de {montant} aide Sochaux Rétro à préserver l'histoire du FCSM.\n\nL'équipe de Sochaux Rétro"],
        ],
    ],
    'mail' => [
        'label' => 'E-mail (SMTP)',
        'fields' => [
            'from_email' => ['label' => 'Adresse d’expédition', 'type' => 'email', 'default' => ''],
            'from_name' => ['label' => 'Nom d’expéditeur', 'type' => 'text', 'default' => 'Sochaux Rétro'],
            'smtp_host' => ['label' => 'Serveur SMTP', 'type' => 'text', 'default' => '', 'help' => 'Vide = fonction mail() de PHP.'],
            'smtp_port' => ['label' => 'Port', 'type' => 'number', 'default' => 587],
            'smtp_secure' => ['label' => 'Sécurité', 'type' => 'select', 'options' => ['tls' => 'STARTTLS (587)', 'ssl' => 'SSL (465)', '' => 'Aucune'], 'default' => 'tls'],
            'smtp_user' => ['label' => 'Identifiant', 'type' => 'text', 'default' => ''],
            'smtp_password' => ['label' => 'Mot de passe', 'type' => 'secret', 'default' => ''],
        ],
    ],
    'newsletter' => [
        'label' => 'Newsletter « Ce jour-là »',
        'fields' => [
            'enabled' => ['label' => 'Envoyer la newsletter automatiquement', 'type' => 'bool', 'default' => false],
            'weekday' => ['label' => 'Jour d’envoi', 'type' => 'select', 'options' => ['1' => 'Lundi', '2' => 'Mardi', '3' => 'Mercredi', '4' => 'Jeudi', '5' => 'Vendredi', '6' => 'Samedi', '7' => 'Dimanche'], 'default' => '1'],
            'hour' => ['label' => 'Heure d’envoi', 'type' => 'number', 'default' => 8],
            'subject' => ['label' => 'Objet', 'type' => 'text', 'default' => 'Ce jour-là · la semaine du {semaine}'],
            'intro' => ['label' => 'Texte d’introduction', 'type' => 'wysiwyg', 'default' => '<p>Voici les matchs de cette semaine dans l’histoire du FC Sochaux-Montbéliard.</p>'],
        ],
    ],
    'map' => [
        'label' => 'Carte',
        'fields' => [
            'geocoding' => ['label' => 'Géolocaliser automatiquement stades et lieux de naissance (OpenStreetMap)', 'type' => 'bool', 'default' => true, 'help' => 'Une requête par seconde au plus, par la tâche planifiée.'],
        ],
    ],
    'centenary' => [
        'label' => 'Centenaire',
        'fields' => [
            'moments_start' => ['label' => 'Date de publication du moment n° 1', 'type' => 'date', 'default' => '2026-06-11', 'help' => 'Un nouveau moment est révélé chaque semaine.'],
            'onze_reveal' => ['label' => 'Date de dévoilement du Onze du public', 'type' => 'date', 'default' => '2028-05-20'],
        ],
    ],
    'legal' => [
        'label' => 'Mentions légales',
        'fields' => [
            'publisher' => ['label' => 'Éditeur du site (nom de l’association)', 'type' => 'text', 'default' => 'Sochaux Rétro'],
            'status' => ['label' => 'Forme juridique', 'type' => 'text', 'default' => '', 'help' => 'Ex. : association régie par la loi du 1er juillet 1901.'],
            'address' => ['label' => 'Adresse du siège', 'type' => 'wysiwyg', 'default' => ''],
            'registration' => ['label' => 'N° RNA ou SIREN', 'type' => 'text', 'default' => ''],
            'director' => ['label' => 'Directeur ou directrice de la publication', 'type' => 'text', 'default' => ''],
            'email' => ['label' => 'E-mail de contact (vide = e-mail général)', 'type' => 'email', 'default' => ''],
            'phone' => ['label' => 'Téléphone (facultatif)', 'type' => 'text', 'default' => ''],
            'host' => ['label' => 'Hébergeur', 'type' => 'wysiwyg', 'default' => '<p>o2switch SAS<br>Chemin des Pardiaux, 63000 Clermont-Ferrand, France<br>Téléphone : 04 44 44 60 40 · www.o2switch.fr</p>'],
            'privacy_contact' => ['label' => 'Contact pour les données personnelles (vide = e-mail de contact)', 'type' => 'email', 'default' => ''],
            'extra' => ['label' => 'Compléments aux mentions légales', 'type' => 'wysiwyg', 'default' => ''],
        ],
    ],
    'backups' => [
        'label' => 'Sauvegardes',
        'fields' => [
            'enabled' => ['label' => 'Sauvegarde automatique quotidienne', 'type' => 'bool', 'default' => true],
            'hour' => ['label' => 'Heure de la sauvegarde', 'type' => 'number', 'default' => 3],
            'keep' => ['label' => 'Nombre de sauvegardes conservées', 'type' => 'number', 'default' => 14],
            'media_weekly' => ['label' => 'Inclure les photos chaque dimanche (archive volumineuse)', 'type' => 'bool', 'default' => false],
        ],
    ],
    'vitrine' => [
        'label' => 'Site de l’association',
        // Réglé dans le pavé « Site de l'association » du back-office (pas dans l'écran Réglages).
        'hidden' => true,
        'fields' => [
            'open' => ['label' => 'Site de l’association ouvert au public', 'type' => 'bool', 'default' => false, 'help' => 'Fermé : les visiteurs voient une page d’attente et rien n’est indexé par les moteurs de recherche. L’aperçu reste disponible depuis le back-office.'],
            'base_url' => ['label' => 'Adresse du site de l’association', 'type' => 'url', 'default' => 'https://www.fcsochauxretro.com', 'help' => 'Sans barre oblique finale. Le domaine doit mener au même dossier que le musée (cPanel › Domaines).'],
            'aliases' => ['label' => 'Autres adresses redirigées vers ce site', 'type' => 'text', 'default' => 'fcsochauxretro.com', 'help' => 'Noms de domaine séparés par des virgules (par exemple l’adresse sans « www »).'],
            'name' => ['label' => 'Nom de l’association', 'type' => 'text', 'default' => 'Sochaux Rétro'],
            'tagline' => ['label' => 'Signature (sous le nom)', 'type' => 'text', 'default' => 'L’association qui fait vivre la mémoire du FC Sochaux-Montbéliard'],
            'email' => ['label' => 'E-mail de réception (adhésions, bénévoles, messages)', 'type' => 'email', 'default' => '', 'help' => 'Vide : l’e-mail de réception du musée (Réglages › Général).'],
            'phone' => ['label' => 'Téléphone affiché (facultatif)', 'type' => 'text', 'default' => ''],
            'address' => ['label' => 'Adresse postale (bulletin d’adhésion, chèques)', 'type' => 'wysiwyg', 'default' => '', 'help' => 'Vide : l’adresse du siège (Réglages › Mentions légales).'],
            'membership_online' => ['label' => 'Adhésion en ligne (carte bancaire, PayPal)', 'type' => 'bool', 'default' => true, 'help' => 'Avec les moyens de paiement des dons (Réglages › Dons). Sans eux, seul le bulletin à imprimer est proposé.'],
            'helloasso' => ['label' => 'Page HelloAsso de l’association (facultatif)', 'type' => 'url', 'default' => '', 'help' => 'Ajoute un bouton « Adhérer avec HelloAsso » sur la page Adhérer.'],
            'linkedin' => ['label' => 'LinkedIn (facultatif)', 'type' => 'url', 'default' => ''],
            'agenda_retro' => ['label' => 'Agenda : ajouter les Rétro-Direct programmés au musée', 'type' => 'bool', 'default' => true],
            'youtube_channel' => ['label' => 'Identifiant de la chaîne YouTube (UC…, facultatif)', 'type' => 'text', 'default' => '', 'help' => 'Pour afficher les dernières vidéos. Vide : retrouvé à partir du lien YouTube des réseaux sociaux.'],
            'seo_title' => ['label' => 'Titre de l’accueil (onglet du navigateur, Google)', 'type' => 'text', 'default' => 'Sochaux Rétro · L’association de la mémoire du FC Sochaux-Montbéliard'],
            'seo_description' => ['label' => 'Description de l’accueil (Google, partage)', 'type' => 'text', 'default' => 'Sochaux Rétro rassemble, préserve et partage l’histoire du FC Sochaux-Montbéliard : musée en ligne, vidéos, archives, rencontres et préparation du centenaire du club en 2028.'],
            'noindex' => ['label' => 'Masquer le site aux moteurs de recherche', 'type' => 'bool', 'default' => false, 'help' => 'Même ouvert, le site n’est pas indexé. Inutile tant qu’il est fermé.'],
        ],
    ],
    'privacy' => [
        'label' => 'Cookies et RGPD',
        'fields' => [
            'cookie_text' => ['label' => 'Texte du bandeau cookies', 'type' => 'wysiwyg', 'default' => 'Nous utilisons des cookies pour lire les vidéos YouTube et traiter les dons en ligne. Vous pouvez accepter ou refuser ces services.'],
            'analytics_id' => ['label' => 'Mesure d’audience (ID, facultatif)', 'type' => 'text', 'default' => ''],
            'legal_page' => ['label' => 'Adresse de la page Mentions légales', 'type' => 'text', 'default' => '/mentions-legales/'],
        ],
    ],
];
